# -*- coding: utf-8 -*-
"""ライダー名の日本語表記（カタカナ。日本人は確かなもののみ漢字）
キーは英字名（アクセント無視・大文字小文字無視で照合）"""
JA = {
# ---- 2002〜2009年 ----
"Sebastian Porto": "セバスチャン・ポルト", "Emilio Alzamora": "エミリオ・アルサモラ", "Roberto Locatelli": "ロベルト・ロカテッリ",
"Haruchika Aoki": "青木治親", "Shahrol Yuzy": "シャロル・ユージー", "Osamu Miyazaki": "ミヤザキ・オサム",
"Daisaku Sakai": "酒井大作", "Leon Haslam": "レオン・ハスラム", "Ralf Waldmann": "ラルフ・ヴァルトマン",
"Dirk Heidolf": "ディルク・ハイドルフ", "Jay Vincent": "ジェイ・ヴィンセント", "Jaroslav Hules": "ヤロスラフ・フレシュ",
"Raul Jara": "ラウル・ハラ", "Choujun Kameya": "亀谷長純", "Erwan Nigon": "エルワン・ニゴン", "Taro Sekiguchi": "関口太郎",
"Vincent Philippe": "ヴァンサン・フィリップ", "Hugo Marchand": "ユーゴ・マルシャン", "Eric Bataille": "エリック・バタイユ",
"Ryuji Yokoe": "横江竜司", "Jakub Smrz": "ヤクブ・スムルツ", "Lucio Cecchinello": "ルーチョ・チェッキネロ",
"Steve Jenkner": "スティーブ・イェンクナー", "Pablo Nieto": "パブロ・ニエト", "Simone Sanna": "シモーネ・サンナ",
"Masao Azuma": "東雅雄", "Gino Borsoi": "ジーノ・ボルソイ", "Joan Olive": "ジョアン・オリベ", "Mirko Giansanti": "ミルコ・ジャンサンティ",
"Stefano Perugini": "ステファノ・ペルジーニ", "Andrea Ballerini": "アンドレア・バッレリーニ", "Stefano Bianco": "ステファノ・ビアンコ",
"Shuhei Aoyama": "青山周平", "Noboru Ueda": "上田昇", "Angel Rodriguez": "アンヘル・ロドリゲス", "Max Sabbatani": "マックス・サッバターニ",
"Klaus Nöhles": "クラウス・ネーレス", "Hideyuki Nakajoh": "ナカジョウ・ヒデユキ", "Christian Pistoni": "クリスティアン・ピストーニ",
"Gioele Pellino": "ジョエレ・ペッリーノ", "Fabrizio Lai": "ファブリツィオ・ライ", "Johan Stigefelt": "ヨハン・スティーゲフェルト",
"Christian Gemmel": "クリスティアン・ゲンメル", "Tekkyu Kayo": "嘉陽哲久", "Masaki Tokudome": "徳留真紀",
"Radomil Rous": "ラドミル・ロウス", "Robbin Harms": "ロビン・ハームス", "Martin Cardenas": "マルティン・カルデナス",
"Gregory Leblanc": "グレゴリー・ルブラン", "Tomoyoshi Koyama": "小山知良", "Lorenzo Zanetti": "ロレンツォ・ザネッティ",
"Toshihisa Kuzuhara": "クズハラ・トシヒサ", "Raffaele De Rosa": "ラファエレ・デ・ローザ", "Manuel Hernandez": "マヌエル・エルナンデス",
"Michael Ranseder": "ミヒャエル・ランゼーダー", "Dan Linfoot": "ダン・リンフット", "Imre Toth": "イムレ・トート",
"Jordi Carchano": "ジョルディ・カルチャノ", "Michele Conti": "ミケーレ・コンティ", "Christian Elkin": "クリスチャン・エルキン",
"Dario Giuseppetti": "ダリオ・ジュゼッペッティ", "Enrique Jerez": "エンリケ・ヘレス", "Arturo Tizon": "アルトゥーロ・ティソン",
"Fabricio Perren": "ファブリシオ・ペレン", "Luca Morelli": "ルカ・モレッリ", "Alvaro Molina": "アルバロ・モリーナ",
"Federico Sandi": "フェデリコ・サンディ", "Hiroaki Kuzuhara": "クズハラ・ヒロアキ", "Ratthapark Wilairot": "ラタパーク・ウィライロー",
"Seijin Oikawa": "オイカワ・セイジン", "Stevie Bonsey": "スティービー・ボンジー", "Georg Fröhlich": "ゲオルク・フレーリッヒ",
"Simone Grotzkyj": "シモーネ・グロツキー", "Daniel Arcas": "ダニエル・アルカス", "Toni Wirsing": "トニ・ヴィルジング",
"Doni Tata Pradita": "ドニ・タタ・プラディタ", "Pere Tutusaus": "ペレ・トゥトゥサウス", "Robin Lässer": "ロビン・レッサー",
"Adrian Martin": "アドリアン・マルティン", "Hugo Van Den Berg": "ユーゴ・ファン・デン・ベルフ", "Valentin Debise": "ヴァランタン・ドゥビーズ",
"Balazs Nemeth": "バラージュ・ネーメト", "Vladimir Leonov": "ウラジーミル・レオノフ", "Bastien Chesaux": "バスティアン・シェソー",
"Toby Markham": "トビー・マーカム", "Riccardo Moretti": "リッカルド・モレッティ", "Jasper Iwema": "ヤスパー・イウェマ",
"Martin Glossop": "マーティン・グロソップ", "Marvin Fritz": "マルビン・フリッツ", "Gregory Di Carlo": "グレゴリー・ディ・カルロ",
"Daniel Kartheininger": "ダニエル・カルトハイニンガー", "Jarno Janssen": "ヤルノ・ヤンセン", "Shinichi Nakatomi": "中冨伸一",
"Thierry van den Bosch": "ティエリー・ファン・デン・ボス", "Peter Politiek": "ペーター・ポリティーク", "Jarno Boesveld": "ヤルノ・ブースフェルト",
"Gert Pieper": "ヘルト・ピーパー", "Andrew Whittley": "アンドリュー・ウィットリー", "Nico Kehrer": "ニコ・ケーラー",
"Henk van de Lagemaat": "ヘンク・ファン・デ・ラーヘマート", "Gabor Rizmayer": "ガーボル・リズマイヤー", "Vladimir Castka": "ウラジミール・チャストカ",
"Gregory Lefort": "グレゴリー・ルフォール", "Nobuyuki Ohsaki": "オオサキ・ノブユキ", "Russell Holland": "ラッセル・ホランド",
"Chuck Sorensen": "チャック・ソレンセン", "Mattia Angeloni": "マッティア・アンジェローニ", "Suhathai Chaemsap": "スハタイ・チェムサップ",
"Jarno Müller": "ヤルノ・ミュラー", "Hideyuki Ogata": "オガタ・ヒデユキ", "Akira Komuro": "コムロ・アキラ", "Ruben Catalan": "ルベン・カタラン",
"Jimmy Petit": "ジミー・プティ", "Yohann Tiberio": "ヨアン・ティベリオ", "Vincent Braillard": "ヴァンサン・ブライヤール",
"Gaspare Caffiero": "ガスパレ・カッフィエーロ", "Marco Petrini": "マルコ・ペトリーニ", "Gianluigi Scalvini": "ジャンルイジ・スカルヴィーニ",
"Alessandro Brannetti": "アレッサンドロ・ブランネッティ", "Adri den Bekker": "アドリ・デン・ベッカー", "Randy Gevers": "ランディ・ヘフェルス",
"Gerald Perdon": "ヘラルト・ペルドン", "Raymond Schouten": "レイモンド・スハウテン", "Ivan Goi": "イヴァン・ゴイ",
"Christopher Martin": "クリストファー・マーティン", "Guy Farbrother": "ガイ・ファーブラザー", "Midge Smart": "ミッジ・スマート",
"Claudius Klein": "クラウディウス・クライン", "Patrick Unger": "パトリック・ウンガー", "Jascha Buech": "ヤシャ・ビュッヒ",
"Matej Smrz": "マテイ・スムルツ", "Manuel Mickan": "マヌエル・ミッカン", "Igor Kalab": "イゴール・カラブ", "Joshua Waters": "ジョシュア・ウォーターズ",
"Peter Holmes": "ピーター・ホームズ", "Jeremy Crowe": "ジェレミー・クロウ", "Chris Peris": "クリス・ペリス", "Katja Poensgen": "カーチャ・ポエンスゲン",
"Luis Castro": "ルイス・カストロ", "Samuel Aubry": "サミュエル・オーブリー", "Christophe Rastel": "クリストフ・ラステル", "Jan Blok": "ヤン・ブロック",
"Arie Vos": "アリー・フォス", "Hans Smees": "ハンス・スメース", "Lee Dickinson": "リー・ディキンソン", "Phillip Desborough": "フィリップ・デスボロー",
"Vesa Kallio": "ヴェサ・カッリオ", "Tomas Palander": "トーマス・パランデル", "Norman Rank": "ノルマン・ランク", "Michal Filla": "ミハル・フィッラ",
"Frederik Watz": "フレデリック・ワッツ", "Miguel Praia": "ミゲル・プライア", "Shi Zhao Huang": "シー・ジャオ・ホアン", "Geoff Hardcastle": "ジェフ・ハードキャッスル",
"Patrick Lakerveld": "パトリック・ラーケルフェルト", "Akio Tanaka": "タナカ・アキオ", "Peter Lenart": "ペーテル・レナールト", "Sadahito Suma": "スマ・サダヒト",
"Ismael Ortega": "イスマエル・オルテガ", "David Bonache": "ダビド・ボナチェ", "William Gautier": "ウィリアム・ゴーティエ", "Xavier Herouin": "グザビエ・エルアン",
"Jarno van der Marel": "ヤルノ・ファン・デル・マレル", "Mark Van Kreij": "マルク・ファン・クレイ", "Paul Veazey": "ポール・ヴィージー",
"Lee Longden": "リー・ロングデン", "Chester Lusk": "チェスター・ラスク", "Kris Weston": "クリス・ウェストン", "Marketa Janakova": "マルケタ・ヤナーコヴァー",
"Luka Nedog": "ルカ・ネドグ", "Vaclav Bittman": "ヴァーツラフ・ビットマン", "Hiroyuki Kikuchi": "キクチ・ヒロユキ", "Manuel Manna": "マヌエル・マンナ",
"Michele Danese": "ミケーレ・ダネーゼ", "Matthew Kuhne": "マシュー・クーン", "Jarno Ronzoni": "ヤルノ・ロンツォーニ", "David Fouloi": "ダヴィド・フロワ",
"Valerio Anghetti": "ヴァレリオ・アンゲッティ", "Yuzo Fujioka": "フジオカ・ユウゾウ", "Marcellino Lucchi": "マルチェリーノ・ルッキ",
"Julian Miralles": "フリアン・ミラレス", "Mathieu Gines": "マチュー・ジネス", "Yannick Deschamps": "ヤニック・デシャン",
"Alessio Aldrovandi": "アレッシオ・アルドロヴァンディ", "Mikko Kyyhkynen": "ミッコ・キュウフキュネン", "Jordi Planas": "ジョルディ・プラナス",
"Thomas Bridewell": "トーマス・ブライドウェル", "Patrik Vostarek": "パトリク・ヴォスターレク", "Shigeki Norikane": "ノリカネ・シゲキ",
"Yuki Hatano": "ハタノ・ユウキ", "Yves Polzer": "イヴ・ポルツァー", "Zi Xian He": "ズー・シエン・ホー", "Gabriele Ferro": "ガブリエレ・フェッロ",
"Andreas Martensson": "アンドレアス・モーテンソン", "Nicklas Cajback": "ニクラス・カイベック", "Thomas Walter": "トーマス・ヴァルター",
"Franz Aschenbrenner": "フランツ・アッシェンブレンナー", "Kouki Takahashi": "タカハシ・コウキ", "Mamoru Akiya": "アキヤ・マモル",
"Zheng Peng Li": "ジェン・ポン・リー", "Zhu Wang": "ジュー・ワン", "Mateo Tunez": "マテオ・トゥネス", "Daniel Saez": "ダニエル・サエス", "Sascha Hommel": "ザシャ・ホンメル",
"Wai On Cheung": "ワイ・オン・チュン", "Ho Wan Chow": "ホー・ワン・チャウ", "Mathieu Lussiana": "マチュー・リュシアナ", "Alexis Michel": "アレクシス・ミシェル",
"Lorenzo Baroni": "ロレンツォ・バローニ", "Luca Verdini": "ルカ・ヴェルディーニ", "Nico Vivarelli": "ニコ・ヴィヴァレッリ", "Gert-Jan Kok": "ヘルト＝ヤン・コック",
"Joey Litjens": "ヨーイ・リッチェンス", "James Westmorland": "ジェームズ・ウェストモーランド", "Rob Guiver": "ロブ・ガイヴァー", "Kev Coghlan": "ケヴ・コグラン",
"Thomas Mayer": "トーマス・マイヤー", "Lukas Razek": "ルカーシュ・ラーゼク", "Yuki Hamamoto": "ハマモト・ユウキ", "Arata Mori": "モリ・アラタ",
"Kazuki Hanafusa": "ハナフサ・カズキ", "Hiroomi Iwata": "イワタ・ヒロオミ", "Blake Leigh-Smith": "ブレイク・リー＝スミス", "Tom Hatton": "トム・ハットン",
"Alessio Palumbo": "アレッシオ・パルンボ", "Sinan Sofuoglu": "シナン・ソフォオール", "Jin Xiao": "ジン・シャオ", "Chi Fung Ho": "チー・フォン・ホー",
"Omar Menghi": "オマール・メンギ", "Bram Appelo": "ブラム・アッペロ", "Jan Roelofs": "ヤン・ルーロフス", "Luke Lawrence": "ルーク・ローレンス",
"Meik Kevin Minnerop": "マイク・ケヴィン・ミネロップ", "Kenni Aggerholm": "ケニ・アガーホルム", "Rong Zai Su": "ロン・ザイ・スー",
"Joao Fernandes": "ジョアン・フェルナンデス", "Santiago Barragan": "サンティアゴ・バラガン", "Roberto Tamburini": "ロベルト・タンブリーニ",
"Ivan Maestro": "イバン・マエストロ", "Dino Lombardi": "ディーノ・ロンバルディ", "Daniele Rossi": "ダニエレ・ロッシ",
"Roberto Lacalendola": "ロベルト・ラカレンドラ", "Robert Muresan": "ロベルト・ムレシャン", "Patrick van de Waarsenburg": "パトリック・ファン・デ・ワールセンブルク",
"Anthony Rogers": "アンソニー・ロジャース", "Kyle Kentish": "カイル・ケンティッシュ", "Daniel Cooper": "ダニエル・クーパー",
"Clement Dunikowski": "クレマン・デュニコフスキ", "Eric Hübsch": "エリック・ヒュープシュ", "Michal Sembera": "ミハル・シェンベラ",
"Michal Prasek": "ミハル・プラーシェク", "Stefano Musco": "ステファノ・ムスコ", "Rhys Moller": "リース・モラー", "Iori Namihira": "ナミヒラ・イオリ",
"Kazuya Otani": "オオタニ・カズヤ", "Thomas Tallevi": "トーマス・タッレヴィ", "Ronald Beitler": "ロナルト・バイトラー", "Thomas Walther": "トーマス・ヴァルター",
"Joshua Sommer": "ヨシュア・ゾンマー", "Tobias Siegert": "トビアス・ジーゲルト", "Alen Gyorfi": "アレン・ジェールフィ", "Romain Maitre": "ロマン・メートル",
"Steven Le Coquen": "スティーヴン・ル・コカン", "Julien Cartron": "ジュリアン・カルトロン", "Simone Sancioni": "シモーネ・サンチョーニ",
"Philipp Eitzinger": "フィリップ・アイツィンガー", "Luke Jones": "ルーク・ジョーンズ", "Nikki Coates": "ニッキー・コーツ", "Robbie Stewart": "ロビー・スチュワート",
"Tom Hayward": "トム・ヘイワード", "Roy Pouw": "ロイ・パウ", "Ferry Stoffer": "フェリー・ストッファー", "Sebastien Eckner": "ゼバスティアン・エックナー",
"Karel Pesek": "カレル・ペシェク", "Karel Majek": "カレル・マイエク", "Ferruccio Lamborghini": "フェルッチョ・ランボルギーニ",
"Federico Biaggi": "フェデリコ・ビアッジ", "Nayuta Mizuno": "ミズノ・ナユタ", "Yuuichi Yanagisawa": "ヤナギサワ・ユウイチ", "Glenn Scott": "グレン・スコット",
"Cyril Carrillo": "シリル・カリーリョ", "Russel Gomez": "ルッセル・ゴメス", "Takumi Endoh": "エンドウ・タクミ", "Yuuki Ito": "イトウ・ユウキ",
"Luca Vitali": "ルカ・ヴィターリ", "Jordi Dalmau": "ジョルディ・ダルマウ", "Lee Costello": "リー・コステロ", "Paul Jordan": "ポール・ジョーダン",
"Connor Behan": "コナー・ビーアン", "Matthew Hoyle": "マシュー・ホイル", "Luke Hinton": "ルーク・ヒントン", "Robert Gull": "ロベルト・グル",
"Ernst Dubbink": "エルンスト・ドゥビンク", "Jerry Van De Bunt": "イェリー・ファン・デ・ブント", "Marco Ravaioli": "マルコ・ラヴァイオーリ",
"Sebastian Kreuziger": "ゼバスティアン・クロイツィガー", "Lukas Sembera": "ルカーシュ・シェンベラ", "Andrea Touskova": "アンドレア・トウシュコヴァー",
"Gennaro Sabatino": "ジェンナーロ・サバティーノ", "PJ Jacobsen": "PJ・ジェイコブセン", "Davide Stirpe": "ダヴィデ・スティルペ",
"Kristian Lee Turner": "クリスチャン・リー・ターナー", "Hiroki Ono": "オノ・ヒロキ", "Jed Metcher": "ジェド・メッチャー", "Brad Gross": "ブラッド・グロス",
"Cristian Trabalon": "クリスティアン・トラバロン", "Joakim Stensmo": "ヨアキム・ステンスモ", "Luke Mossey": "ルーク・モッシー", "Barrett Long": "バレット・ロング",
"Adam Roberts": "アダム・ロバーツ", "Christopher Moretti": "クリストファー・モレッティ", "William Dunlop": "ウィリアム・ダンロップ",
"Luca Marconi": "ルカ・マルコーニ", "Satoru Kamada": "カマダ・サトル", "Yuki Oogane": "オオガネ・ユウキ", "Yuma Yahagi": "ヤハギ・ユウマ",
"Borja Maestro": "ボルハ・マエストロ", "Eduard Lopez": "エドゥアルド・ロペス", "Sturla Fagerhaug": "ストゥルラ・ファーゲルハウグ",
"Luigi Morciano": "ルイジ・モルチャーノ", "Johnny Rosell": "ジョニー・ロセル", "Pepijn Bijsterbosch": "ペペイン・ベイスターボス",
"Toni Finsterbusch": "トニ・フィンスターブッシュ", "Damien Raemy": "ダミアン・レミー", "Eeki Kuparinen": "エーキ・クパリネン", "James Lodge": "ジェームズ・ロッジ",
"Timothy Hastings": "ティモシー・ヘイスティングス", "Ivan Visak": "イヴァン・ヴィシャク", "Ladislav Chmelik": "ラジスラフ・フメリーク",
"Miles Thornton": "マイルズ・ソーントン", "Jacub Jantulik": "ヤクブ・ヤントゥリーク", "Quentin Jacquet": "カンタン・ジャケ", "Andrew Lawson": "アンドリュー・ローソン",
"Levi Day": "リーヴァイ・デイ", "Nicky Diles": "ニッキー・ダイルズ", "Elly Ilias": "エリー・イリアス", "Ben Young": "ベン・ヤング", "Gergo Talmacsi": "ゲルゲー・タルマーチ", "Kazuma Watanabe": "ワタナベ・カズマ", "Aitor Rodriguez": "アイトール・ロドリゲス", "Joan Perello": "ジョアン・ペレリョ",
}
JA.update({
# ---- 2010〜2025年 ----
"Kenny Noyes": "ケニー・ノイズ", "Jason Di Salvo": "ジェイソン・ディサルボ", "Vladimir Ivanov": "ウラジーミル・イワノフ", "Arne Tode": "アルネ・トーデ",
"Robertino Pietri": "ロベルティーノ・ピエトリ", "Yusuke Teshima": "テシマ・ユウスケ", "Taylor Mackenzie": "テイラー・マッケンジー",
"Manuel Tatasciore": "マヌエル・タタショーレ", "Harry Stafford": "ハリー・スタッフォード", "Miroslav Popov": "ミロスラフ・ポポフ",
"Josep Rodriguez": "ジョセップ・ロドリゲス", "Giulian Pedone": "ジュリアン・ペドーネ", "Dani Rivas": "ダニ・リバス", "Eric Granado": "エリック・グラナド",
"Alessandro Andreozzi": "アレッサンドロ・アンドレオッツィ", "Roman Ramos": "ロマン・ラモス", "Rafid Topan Sucipto": "ラフィド・トパン・スチプト",
"Alan Techer": "アラン・テシェ", "Ivan Moreno": "イバン・モレノ", "Luca Grünwald": "ルカ・グリュンヴァルト", "Kevin Hanus": "ケヴィン・ハヌス",
"Kevin Calia": "ケヴィン・カリア", "Michael Ruben Rinaldi": "ミケーレ・ルーベン・リナルディ", "Alex Mariñelarena": "アレックス・マリニェラレナ",
"Steven Odendaal": "スティーヴン・オーデンダール", "Azlan Shah": "アズラン・シャー", "Ezequiel Iturrioz": "エセキエル・イトゥリオス",
"Lucas Mahias": "リュカ・マイアス", "Ana Carrasco": "アナ・カラスコ", "Matteo Ferrari": "マッテオ・フェラーリ", "Hyuga Watanabe": "ワタナベ・ヒュウガ",
"Hafiq Azmi": "ハフィク・アズミ", "Robin Mulhauser": "ロビン・ミュルハウザー", "Maria Herrera": "マリア・エレーラ", "Manuel Pagliani": "マヌエル・パリアーニ",
"Ramdan Rosli": "ラムダン・ロスリ", "Edgar Pons": "エドガー・ポンス", "Federico Fuligni": "フェデリコ・フリーニ", "Naomichi Uramoto": "ウラモト・ナオミチ",
"Danny Eslick": "ダニー・エスリック", "Hugo Clere": "ユーゴ・クレール", "Stefano Valtulini": "ステファノ・ヴァルトゥリーニ",
"Lorenzo Petrarca": "ロレンツォ・ペトラルカ", "Fabio Spiranelli": "ファビオ・スピラネッリ", "Maximilian Kappler": "マクシミリアン・カップラー",
"Matt Barton": "マット・バートン", "Davide Pizzoli": "ダヴィデ・ピッツォーリ", "Tim Georgi": "ティム・ゲオルギ", "Enzo Boulom": "エンゾ・ブロム",
"Vicente Perez": "ビセンテ・ペレス", "Shizuka Okazaki": "オカザキ・シズカ", "Gabriel Martinez-Abrego": "ガブリエル・マルティネス＝アブレゴ",
"Ikuhiro Enokido": "エノキド・イクヒロ", "Tarran Mackenzie": "タラン・マッケンジー", "Ryo Mizuno": "ミズノ・リョウ", "Axel Bassani": "アクセル・バッサーニ",
"Nakarin Atiratphuvapat": "ナカリン・アティラットプワパット", "Kazuki Masaki": "マサキ・カズキ", "Alex Fabbri": "アレックス・ファッブリ",
"Tom Booth-Amos": "トム・ブース＝エイモス", "Patrik Pulkkinen": "パトリック・プルッキネン", "Tom Toparis": "トム・トパリス",
"Maximilian Kofler": "マクシミリアン・コフラー", "Aaron Polanco": "アーロン・ポランコ", "Aleix Viu": "アレイシ・ビウ", "Niki Tuuli": "ニキ・トゥーリ",
"Xavi Cardelus": "シャビ・カルデルス", "Thitipong Warokorn": "ティティポン・ワロコーン", "Lukas Tulovic": "ルーカス・トゥロヴィッチ",
"Dimas Ekky Pratama": "ディマス・エッキー・プラタマ", "Tommaso Marcon": "トンマーゾ・マルコン", "Alejandro Medina": "アレハンドロ・メディナ",
"Sheridan Morais": "シェリダン・モライス", "Corentin Perolari": "コランタン・ペロラリ", "Cedric Tangre": "セドリック・タングル", "Can Öncü": "ジャン・オンジュ",
"Makar Yurchenko": "マカール・ユルチェンコ", "Yari Montella": "ヤリ・モンテッラ", "Apiwath Wongthananon": "アピワット・ウォンタナノン",
"Kevin Zannoni": "ケヴィン・ザンノーニ", "Izam Ikmal": "イザム・イクマル", "Yuto Fukushima": "フクシマ・ユウト", "Ryan Van De Lagemaat": "ライアン・ファン・デ・ラーヘマート",
"Gabriele Ruiu": "ガブリエレ・ルイウ", "Andi Farid Izdihar": "アンディ・ファリド・イズディハル", "Teppei Nagoe": "ナゴエ・テッペイ", "Gerry Salim": "ゲリー・サリム",
"Sean Dylan Kelly": "ショーン・ディラン・ケリー", "Elia Bartolini": "エリア・バルトリーニ", "Rogan Chandler": "ローガン・チャンドラー",
"Gerard Riu Male": "ジェラール・リウ・マレ", "Jose Julian Garcia": "ホセ・フリアン・ガルシア", "Meikon Kawakami": "メイコン・カワカミ",
"Dirk Geiger": "ディルク・ガイガー", "Brandon Paasch": "ブランドン・パーシュ", "Mattia Casadei": "マッティア・カサデイ", "Josh Hook": "ジョシュ・フック",
"Kenny Foray": "ケニー・フォレ", "Kasma Daniel": "カスマ・ダニエル", "Piotr Biesiekirski": "ピョトル・ビェシェキルスキ", "Yuki Kunii": "クニイ・ユウキ",
"Jason Dupasquier": "ジェイソン・デュパスキエ", "Alessandro Zaccone": "アレッサンドロ・ザッコーネ", "Miquel Pons": "ミケル・ポンス",
"Fraser Rogers": "フレイザー・ロジャース", "Taiga Hada": "ハダ・タイガ", "Keminth Kubo": "ケミン・クボ", "Syarifuddin Azman": "シャリフディン・アズマン",
"Alberto Surra": "アルベルト・スッラ", "Lorenzo Fellon": "ロレンゾ・フェロン", "Takuma Matsuyama": "マツヤマ・タクマ", "Mario Aji": "マリオ・アジ",
"David Salvador": "ダビド・サルバドール", "Hikari Okubo": "オオクボ・ヒカリ", "Andrea Mantovani": "アンドレア・マントヴァーニ", "Andre Pires": "アンドレ・ピレス",
"Borja Gomez": "ボルハ・ゴメス", "Zonta van den Goorbergh": "ゾンタ・ファン・デン・フーアベルフ", "Alex Escrig": "アレックス・エスクリグ",
"Rory Skinner": "ローリー・スキナー", "Alex Toledo": "アレックス・トレド", "Azroy Anuar": "アズロイ・アヌアル", "Nicola Carraro": "ニコラ・カッラーロ",
"Joshua Whatley": "ジョシュア・ワトリー", "Marc Garcia": "マルク・ガルシア", "Harrison Voight": "ハリソン・ヴォイト", "Alessandro Morosi": "アレッサンドロ・モロージ",
"Kevin Manfredi": "ケヴィン・マンフレーディ", "Marc Alcoba": "マルク・アルコバ", "Alessio Finello": "アレッシオ・フィネッロ", "Massimo Roccoli": "マッシモ・ロッコリ",
"Unai Orradre": "ウナイ・オラドレ", "Yeray Ruiz": "イェライ・ルイス", "Mattia Rato": "マッティア・ラト", "Soichiro Minamimoto": "ミナミモト・ソウイチロウ",
"David Sanchis": "ダビド・サンチス", "Helmi Azman": "ヘルミ・アズマン", "Arbi Aditama": "アルビ・アディタマ", "Tatchakorn Buasri": "タッチャコーン・ブアシー",
"Danial Shahril": "ダニアル・シャフリル", "Noah Dettwiler": "ノア・デットヴィラー", "Marcos Ruda": "マルコス・ルダ", "Krittapat Keankum": "クリッタパット・キアンカム",
"Nicholas Spinelli": "ニコラス・スピネッリ", "Mika Perez": "ミカ・ペレス", "Luca Salvadori": "ルカ・サルヴァドーリ", "Oscar Gutierrez": "オスカル・グティエレス",
"Roberto Garcia": "ロベルト・ガルシア", "Xabi Zurutuza": "シャビ・スルトゥサ", "Eddie O'Shea": "エディ・オシェイ", "Jakob Rosenthaler": "ヤコブ・ローゼンターラー",
"Rei Wakamatsu": "ワカマツ・レイ", "Hamad Al Sahouti": "ハマド・アル・サフーティ", "Marcos Uriarte": "マルコス・ウリアルテ", "Armando Pontone": "アルマンド・ポントーネ",
"Adrian Huertas": "アドリアン・ウエルタス", "Eric Fernandez": "エリック・フェルナンデス", "Alberto Ferrandez": "アルベルト・フェランデス",
"Marco Morelli": "マルコ・モレッリ", "Casey O'Gorman": "ケイシー・オゴーマン", "Adrian Cruces": "アドリアン・クルセス", "Ruche Moodley": "ルーシュ・ムードリー",
"Brian Uriarte": "ブライアン・ウリアルテ", "Jesus Rios": "ヘスス・リオス", "Hakim Danish": "ハキム・ダニッシュ", "Lenoxx Phommara": "レノックス・ポンマラ",
"Zen Mitani": "ミタニ・ゼン", "Leonardo Abruzzo": "レオナルド・アブルッツォ", "Max Cook": "マックス・クック", "Jacopo Hosciuc": "ヤコポ・ホシュク",
"Luca Bernardi": "ルカ・ベルナルディ", "Tibor Varga": "ティボル・ヴァルガ", "Raffaele Fusco": "ラファエレ・フスコ", "Tommaso Occhi": "トンマーゾ・オッキ",
"Diego Perez": "ディエゴ・ペレス", "Anthony Delhalle": "アントニー・デラール", "Bernat Martinez": "ベルナト・マルティネス", "Yannick Guerra": "ヤニック・ゲラ",
"Mashel Al Naimi": "マシェル・アル・ナイミ", "Amadeo Llados": "アマデオ・リャドス", "Carmelo Morales": "カルメロ・モラレス",
"Tatsuya Yamaguchi": "ヤマグチ・タツヤ", "Santiago Hernandez": "サンティアゴ・エルナンデス", "Hiromichi Kunikawa": "クニカワ・ヒロミチ",
"Mohamad Zamri Baba": "モハマド・ザムリ・ババ", "Alexander Cudlin": "アレクサンダー・カドリン", "Wayne Maxwell": "ウェイン・マクスウェル",
"Kevin Szalai": "ケヴィン・サライ", "Morgan Berchet": "モルガン・ベルシェ", "Mattia Tarozzi": "マッティア・タロッツィ", "Tommaso Gabrielli": "トンマーゾ・ガブリエッリ",
"Deane Brown": "ディーン・ブラウン", "Peter Sebestyen": "ペーテル・シェベシュティエーン", "Francesco Mauriello": "フランチェスコ・マウリエッロ",
"Giovanni Bonati": "ジョヴァンニ・ボナーティ", "Robin Barbosa": "ロバン・バルボザ", "Alejandro Pardo": "アレハンドロ・パルド", "Pedro Rodriguez": "ペドロ・ロドリゲス",
"Takehiro Yamamoto": "ヤマモト・タケヒロ", "Syunya Mori": "モリ・シュンヤ", "Sasuke Shinozaki": "シノザキ・サスケ", "Joel Taylor": "ジョエル・テイラー",
"Nasser Al Malki": "ナセル・アル・マルキ", "Lukasz Wargala": "ウカシュ・ヴァルガワ", "Tommaso Lorenzetti": "トンマーゾ・ロレンツェッティ", "JD Beach": "JD・ビーチ",
"Jacob Gagne": "ジェイコブ・ガニエ", "Elena Rosell": "エレナ・ロセル", "Oscar Climent": "オスカル・クリメント", "Daniel Ruiz": "ダニエル・ルイス",
"Sarath Kumar": "サラス・クマール", "Kevin Thobois": "ケヴィン・トボワ", "Bryan Schouten": "ブライアン・スハウテン", "Thomas Van Leeuwen": "トーマス・ファン・レーウェン",
"Massimo Parziani": "マッシモ・パルツィアーニ", "Felix Forstenhaeusler": "フェリックス・フォルステンホイスラー", "Alessandro Giorgi": "アレッサンドロ・ジョルジ",
"Luca Fabrizio": "ルカ・ファブリツィオ", "Jun Ohnishi": "オオニシ・ジュン", "Marco Colandrea": "マルコ・コランドレア", "Farid Badrul": "ファリド・バドルル",
"Alexander Lundh": "アレクサンダー・ルンド", "Kevin Wahr": "ケヴィン・ヴァール", "Markus Reiterberger": "マルクス・ライターベルガー", "Kenta Fujii": "フジイ・ケンタ",
"Luca Amato": "ルカ・アマート", "Yuudai Kamei": "カメイ・ユウダイ", "Lincoln Gilding": "リンカーン・ギルディング", "Sam Clarke": "サム・クラーク",
"Kyle Smith": "カイル・スミス", "James Rispoli": "ジェームズ・リスポリ", "Jason O'Halloran": "ジェイソン・オハロラン", "Zaqhwan Zaidi": "ザクワン・ザイディ",
"Decha Kraisart": "デチャ・クライサート", "Fadli Immammuddin": "ファドリ・イマムディン", "Florian Alt": "フロリアン・アルト", "Christophe Arciero": "クリストフ・アルシエロ",
"Michael Coletti": "ミケーレ・コレッティ", "Kyle Ryde": "カイル・ライド", "Wayne Ryan": "ウェイン・ライアン", "Aizat Malik": "アイザット・マリク",
"Lachlan Kavney": "ラクラン・カヴニー", "Sena Yamada": "ヤマダ・セナ", "Josh Herrin": "ジョシュ・ヘリン", "Nina Prinz": "ニーナ・プリンツ",
"Riccardo Russo": "リッカルド・ルッソ", "Dakota Mamola": "ダコタ・マモラ", "Florian Marino": "フロリアン・マリノ", "Federico Caricasulo": "フェデリコ・カリカズーロ",
"Chalermpol Polamai": "チャルームポン・ポラマイ", "Aiden Wagner": "エイデン・ワグナー", "Max Croker": "マックス・クローカー", "Scott Deroue": "スコット・デルー",
"Gabriel Ramos": "ガブリエル・ラモス", "Simone Mazzola": "シモーネ・マッツォーラ", "Anthony Groppi": "アンソニー・グロッピ", "Joe Irving": "ジョー・アーヴィング",
"Olly Simpson": "オリー・シンプソン", "Hafiza Rofa": "ハフィザ・ロファ", "Louis Bulle": "ルイ・ビュル", "Bradley Ray": "ブラッドリー・レイ",
"Loris Cresson": "ロリス・クレソン", "Jorel Boerboom": "ヨレル・ブールボーム", "Jonas Geitner": "ヨナス・ガイトナー", "Luke Hedger": "ルーク・ヘッジャー",
"Taz Taylor": "タズ・テイラー", "Adrian Gyutai": "アドリアン・ジュタイ", "Keisuke Kurihara": "クリハラ・ケイスケ", "Alessandro Nocco": "アレッサンドロ・ノッコ",
"Saeed Al Sulaiti": "サイード・アル・スライティ", "Edoardo Sintoni": "エドアルド・シントーニ", "Jake Archer": "ジェイク・アーチャー", "Yanni Shaw": "ヤンニ・ショー",
"Kanta Hamada": "ハマダ・カンタ", "Milan Pawelec": "ミラン・パヴェレツ", "Evan Belford": "エヴァン・ベルフォード",
})
JA.update({
# ---- 1990〜2001年 ----
"Achim Kariger": "アヒム・カリガー", "Adi Stadler": "アディ・シュタードラー", "Adrian Araujo": "アドリアン・アラウホ", "Adrian Bosshard": "アドリアン・ボスハルト",
"Adrian Coates": "エイドリアン・コーツ", "Adrian Schmidt": "アドリアン・シュミット", "Adrien Morillas": "アドリアン・モリヤス", "Agustin Escobar": "アグスティン・エスコバル",
"Ahmed Jayadi": "アフマド・ジャヤディ", "Akio Mitoma": "ミトマ・アキオ", "Akira Saito": "サイトウ・アキラ", "Alain Bronec": "アラン・ブロネック",
"Alan Carter": "アラン・カーター", "Alan Patterson": "アラン・パターソン", "Alberto Puig": "アルベルト・プーチ", "Alberto Rota": "アルベルト・ロータ",
"Alessandro Antonello": "アレッサンドロ・アントネッロ", "Alessandro Gramigni": "アレッサンドロ・グラミーニ", "Alessandro Romagnoli": "アレッサンドロ・ロマニョーリ",
"Alex Criville": "アレックス・クリビーレ", "Alex Sirera": "アレックス・シレラ", "Alexander Folger": "アレクサンダー・フォルガー",
"Alexander Witting": "アレクサンダー・ヴィッティング", "Alexander di Grandi": "アレシャンドリ・ジ・グランジ", "Alfred Waibel": "アルフレート・ヴァイベル",
"Allan Scott": "アラン・スコット", "Andi Notman": "アンディ・ノットマン", "Andre Romein": "アンドレ・ロメイン", "Andrea Borgonovo": "アンドレア・ボルゴノーヴォ",
"Andrea Iommi": "アンドレア・イオンミ", "Andrea Zappa": "アンドレア・ザッパ", "Andreas Göbel": "アンドレアス・ゲーベル", "Andreas Hahn": "アンドレアス・ハーン",
"Andreas Meklau": "アンドレアス・メクラウ", "Andres Sanchez": "アンドレス・サンチェス", "Andrew Palmer": "アンドリュー・パーマー",
"Andrew Stroud": "アンドリュー・ストラウド", "Andrew Willy": "アンドリュー・ウィリー", "Andrie Nijenhuis": "アンドリー・ナイエンハウス",
"Andy Leuthe": "アンディ・ロイテ", "Andy Preining": "アンディ・プライニング", "Angel Nieto Jr.": "アンヘル・ニエト・ジュニア", "Anseimo Lasaosa": "アンセルモ・ラサオサ",
"Anthony Gobert": "アンソニー・ゴバート", "Antonio Elias": "アントニオ・エリアス", "Antonio Garcia": "アントニオ・ガルシア", "Antonio Irizar": "アントニオ・イリサル",
"Antonio Sanchez": "アントニオ・サンチェス", "Arie Molenaar": "アリー・モレナール", "Arief Budiman": "アリフ・ブディマン", "Armando Narduzzi": "アルマンド・ナルドゥッツィ",
"Arno Visscher": "アルノ・フィッセル", "Arnold Litjens": "アルノルト・リッチェンス", "Attila Szabo": "アッティラ・サボー", "Bady Hassaine": "バディ・ハサイン",
"Barry Veneman": "バリー・フェネマン", "Bas Den Breejen": "バス・デン・ブレージェン", "Beaumont Levy": "ボーモント・レヴィ", "Benjamin Weiss": "ベンヤミン・ヴァイス",
"Benny Jerzenbeck": "ベニー・イェルツェンベック", "Bernard Cazade": "ベルナール・カザード", "Bernard Garcia": "ベルナール・ガルシア", "Bernard Haenggeli": "ベルナール・ヘンゲリ",
"Bernd Holzleitner": "ベルント・ホルツライトナー", "Bernd Kassner": "ベルント・カスナー", "Bernhard Absmeier": "ベルンハルト・アプスマイヤー", "Bert Smit": "ベルト・スミット",
"Bertrand Stey": "ベルトラン・ステイ", "Bohumil Stasa Jr.": "ボフミル・スタシャ・ジュニア", "Bohumil Stasa": "ボフミル・スタシャ", "Bohuslav Seifert": "ボフスラフ・サイフェルト",
"Brendan Clarke": "ブレンダン・クラーク", "Brendon Crookes": "ブレンドン・クルックス", "Brian Morrison": "ブライアン・モリソン", "Bruno Bonhuil": "ブルーノ・ボニュイ",
"Bruno Casanova": "ブルーノ・カサノヴァ", "Bruno Vecchioni": "ブルーノ・ヴェッキオーニ", "Callum Ramsay": "カラム・ラムジー", "Carl Fogarty": "カール・フォガティ",
"Carlos Cardús": "カルロス・カルダス", "Carlos Giro Jr.": "カルロス・ヒロ・ジュニア", "Carlos Lavado": "カルロス・ラバード", "Cath Thompson": "キャス・トンプソン",
"Cees Doorakkers": "ケース・ドーラッカース", "Cesar Barros": "セザール・バロス", "Chao Chee Hou": "チャオ・チー・ホウ", "Chee Kieong Soong": "チー・キョン・スーン",
"Chow Yan Kit": "チョウ・ヤン・キット", "Chris D'Aluisio": "クリス・ダルイジオ", "Chris Palmer": "クリス・パーマー", "Chris Walker": "クリス・ウォーカー",
"Christian Boudinot": "クリスチャン・ブディノ", "Christian Kellner": "クリスティアン・ケルナー", "Christian Manna": "クリスティアン・マンナ",
"Christian Sarron": "クリスチャン・サロン", "Christophe Cogan": "クリストフ・コガン", "Claude Arciero": "クロード・アルシエロ", "Claudio Cipriani": "クラウディオ・チプリアーニ",
"Claudio Tonnini": "クラウディオ・トンニーニ", "Claudio Vanzetta": "クラウディオ・ヴァンツェッタ", "Clive Horton": "クライヴ・ホートン", "Colin Clark": "コリン・クラーク",
"Corrado Catalano": "コッラード・カタラーノ", "Craig Connell": "クレイグ・コネル", "Cristian Magnani": "クリスティアン・マニャーニ", "Cristiano Migliorati": "クリスティアーノ・ミリオラーティ",
"Cristiano Vieira": "クリスチアーノ・ヴィエイラ", "Damaso Nacher": "ダマソ・ナチェル", "Damon Buckmaster": "デイモン・バックマスター", "Daniel Amatriain": "ダニエル・アマトリアイン",
"Daniel Piñera": "ダニエル・ピニェラ", "Daniel Ribalta": "ダニエル・リバルタ", "Daniela Tognoli": "ダニエラ・トニョーリ", "Danny Walker": "ダニー・ウォーカー",
"Dario Marchetti": "ダリオ・マルケッティ", "Darren Barton": "ダレン・バートン", "Darren Dixon": "ダレン・ディクソン", "Darren Milner": "ダレン・ミルナー",
"Daryl Beattie": "ダリル・ビーティー", "David Evelyn": "デヴィッド・エヴリン", "David Guardiola": "ダビド・グアルディオラ", "David Horton": "デヴィッド・ホートン",
"David Jefferies": "デヴィッド・ジェフリーズ", "David Mateer": "デヴィッド・マティアー", "David Mayne": "デヴィッド・メイン", "David Mico": "ダビド・ミコ",
"David Moore": "デヴィッド・ムーア", "David Ortega": "ダビド・オルテガ", "David Tomas": "ダビド・トマス", "Davide Bulega": "ダヴィデ・ブレガ",
"Decha Krisart": "デチャ・クリサート", "Dennis Charlett": "デニス・シャーレット", "Didier De Radigues": "ディディエ・ド・ラディゲ", "Diego Giugovaz": "ディエゴ・ジュゴヴァツ",
"Diego Pierluiggi": "ディエゴ・ピエルルイジ", "Diego Ruaben": "ディエゴ・ルアベン", "Direk Archewong": "ディレク・アチェウォン", "Dirk Brockman": "ディルク・ブロックマン",
"Dirk Raudies": "ディルク・ラウディス", "Dirk Reissmann": "ディルク・ライスマン", "Domenico Brigaglia": "ドメニコ・ブリガーリア", "Dominique Sarron": "ドミニク・サロン",
"Donnie Hough": "ドニー・ハフ", "Doriano Romboni": "ドリアーノ・ロンボーニ", "Doug Chandler": "ダグ・チャンドラー", "Eddie Lawson": "エディ・ローソン",
"Eddie Laycock": "エディ・レイコック", "Emanuel Buchner": "エマヌエル・ブフナー", "Emilio Cuppini": "エミリオ・クッピーニ", "Emilio Delgado": "エミリオ・デルガド",
"Enrique de Juan": "エンリケ・デ・フアン", "Eric Dubray": "エリック・デュブレ", "Erich Neumair": "エーリッヒ・ノイマイヤー", "Erkka Korpiaho": "エルッカ・コルピアホ",
"Ermanno Bastianini": "エルマンノ・バスティアニーニ", "Ernesto Vidal": "エルネスト・ビダル", "Eskil Suter": "エスキル・ズッター", "Esko Kuparinen": "エスコ・クパリネン",
"Eugene McManus": "ユージン・マクマナス", "Eustaquio Gavira": "エウスタキオ・ガビラ", "Evren Bischoff": "エヴレン・ビショフ", "Ezio Gianola": "エツィオ・ジャノーラ",
"Fabien Rousseau": "ファビアン・ルソー", "Fabio Carpani": "ファビオ・カルパーニ", "Fabrizio De Marco": "ファブリツィオ・デ・マルコ", "Fausto Gresini": "ファウスト・グレシーニ",
"Fausto Ricci": "ファウスト・リッチ", "Federico Cerroni": "フェデリコ・チェッローニ", "Federico Gartner": "フェデリコ・ガルトネル", "Felipe Horta": "フェリペ・オルタ",
"Felisberto Teixeira": "フェリスベルト・テイシェイラ", "Fernando Cristóbal": "フェルナンド・クリストバル", "Fernando Mendes": "フェルナンド・メンデス", "Filippo Cotti": "フィリッポ・コッティ",
"Flemming Kistrup": "フレミング・キストルプ", "Florian Ferracci": "フロリアン・フェラッシ", "Fokko Kuiper": "フォッコ・カイパー", "Francesco Monaco": "フランチェスコ・モナコ",
"Francisco Debon": "フランシスコ・デボン", "Francisco Padro": "フランシスコ・パドロ", "Francisco Riquelme": "フランシスコ・リケルメ", "Franck Poulle": "フランク・プール",
"Frank Baldinger": "フランク・バルディンガー", "Freddie Spencer": "フレディ・スペンサー", "Frederic Boutin": "フレデリック・ブータン", "Frederic Petit": "フレデリック・プティ",
"Frederic Protat": "フレデリック・プロタ", "Fuyuki Yamazaki": "ヤマザキ・フユキ", "Gabriel Borgmann": "ガブリエル・ボルグマン", "Gabriele Debbia": "ガブリエレ・デッビア",
"Gary Haslam": "ゲイリー・ハスラム", "Gary Jackson": "ゲイリー・ジャクソン", "Gary May": "ゲイリー・メイ", "Gavin Johnston": "ギャヴィン・ジョンストン",
"Georg Scharl": "ゲオルク・シャール", "Gerard Rike": "ヘラルト・ライケ", "Gerwin Hofer": "ゲルヴィン・ホーファー", "Gian Calabrezzi": "ジアン・カラブレッツィ",
"Gianmaria Liverani": "ジャンマリア・リヴェラーニ", "Gilbert De Rover": "ヒルベルト・デ・ローフェル", "Gilles Ferstler": "ジル・フェルストレ", "Gimmi Bosio": "ジミー・ボジオ",
"Giovanni Palmieri": "ジョヴァンニ・パルミエーリ", "Giuseppe Fiorillo": "ジュゼッペ・フィオリッロ", "Glen Richards": "グレン・リチャーズ", "Gregory Fouet": "グレゴリー・フエ",
"Guillaume Dietrich": "ギヨーム・ディートリッヒ", "Hans Becker": "ハンス・ベッカー", "Hans Koopman": "ハンス・コープマン", "Hans Maxwald": "ハンス・マックスヴァルト",
"Hans Spaan": "ハンス・スパーン", "Hans Wieser": "ハンス・ヴィーザー", "Hansjörg Butz": "ハンスイェルク・ブッツ", "Harald Danninger": "ハラルト・ダニンガー",
"Harald Eckl": "ハラルト・エックル", "Harold De Haan": "ハロルト・デ・ハーン", "Hayden Bool": "ヘイデン・ブール", "Heinz Lüthi": "ハインツ・リュティ",
"Helmut Bradl": "ヘルムート・ブラドル", "Helmut Schutz": "ヘルムート・シュッツ", "Herri Torrontegui": "エリ・トロンテギ", "Herve Duffard": "エルヴェ・デュファール",
"Herve Louiset": "エルヴェ・ルイゼ", "Herve Mora": "エルヴェ・モラ", "Hervi Moineau": "エルヴェ・モワノー", "Hikaru Miyagi": "宮城光",
"Hisashi Unemoto": "ウネモト・ヒサシ", "Hubert Abold": "フーベルト・アボルト", "Ian McConnachie": "イアン・マッコナキー", "Ian Newton": "イアン・ニュートン",
"Idalio Gavira": "イダリオ・ガビラ", "Igor Antonelli": "イーゴル・アントネッリ", "Irvan Octavianus": "イルヴァン・オクタヴィアヌス", "Ismael Bonilla": "イスマエル・ボニーリャ",
"Ivan Clementi": "イヴァン・クレメンティ", "Ivan Cremonini": "イヴァン・クレモニーニ", "Ivan Martinez": "イバン・マルティネス", "Ivan Mengozzi": "イヴァン・メンゴッツィ",
"Ivan Tschudin": "イヴァン・チューディン", "J.R. Hazelden": "J.R.・ヘイゼルデン", "Jaap Hoogeveen": "ヤープ・ホーヘフェーン", "Jacques Cornu": "ジャック・コルニュ",
"Jaime Mariano": "ハイメ・マリアノ", "James Armstrong": "ジェームズ・アームストロング", "Jamie Robinson": "ジェイミー・ロビンソン", "Jamie Whitham": "ジェイミー・ウィッタム",
"Janez Pintar": "ヤネズ・ピンタル", "Jason Davis": "ジェイソン・デイビス", "Javier Diaz": "ハビエル・ディアス", "Javier Marsella": "ハビエル・マルセリャ",
"Javier Rodriguez": "ハビエル・ロドリゲス", "Jay Taylor": "ジェイ・テイラー", "Jean Claude Selini": "ジャン＝クロード・セリーニ", "Jean Foray": "ジャン・フォレ",
"Jean Luc Romanens": "ジャン＝リュック・ロマナン", "Jean Philippe Ruggia": "ジャン＝フィリップ・ルジア", "Jean Pierre Jeandat": "ジャン＝ピエール・ジャンダ",
"Jean-Marc Deletang": "ジャン＝マルク・ドレタン", "Jehan D'Orgeix": "ジャン・ドルジェ", "Jeronimo Vidal": "ヘロニモ・ビダル", "Jesús Perez": "ヘスス・ペレス",
"Jim Falls": "ジム・フォールズ", "Jim Filice": "ジム・フィリス", "Joachim Leitert": "ヨアヒム・ライテルト", "Joaquin Perera": "ホアキン・ペレラ",
"Jochen Schmid": "ヨッヘン・シュミート", "John Kocinski": "ジョン・コシンスキー", "John McGuinness": "ジョン・マクギネス", "John Pearson": "ジョン・ピアソン",
"John Reynolds": "ジョン・レイノルズ", "Johnny Wickström": "ヨニー・ヴィクストレム", "Jon Cornwell": "ジョン・コーンウェル", "Jonathan Van Vuuren": "ジョナサン・ファン・フューレン",
"Jonnie Boerman": "ヨニー・ブールマン", "Jorge Martinez": "ホルヘ・マルティネス", "Jos Van Dongen": "ヨス・ファン・ドンゲン", "Jose Barresi": "ホセ・バレシ",
"Jose Kuhn": "ジョゼ・キューン", "Jose Morillas": "ホセ・モリヤス", "Jose Ramon Ramirez": "ホセ・ラモン・ラミレス", "Josef Doppler": "ヨーゼフ・ドップラー",
"Josep Sarda": "ジョセップ・サルダ", "Joshua Brookes": "ジョシュア・ブルックス", "José L. Nion": "ホセ・L・ニオン", "José Leite": "ジョゼ・レイテ",
"Juan Borja": "フアン・ボルハ", "Juan Enrique Maturana": "フアン・エンリケ・マトゥラナ", "Juan Garriga": "フアン・ガリガ", "Juan Lopez Mella": "フアン・ロペス・メリャ",
"Juan Pablo Gianini": "フアン・パブロ・ジャニーニ", "Juanlino Kirindongo": "フアンリノ・キリンドンゴ", "Judd Greedy": "ジャッド・グリーディ", "Juergen Lingg": "ユルゲン・リング",
"Julien Allemand": "ジュリアン・アルマン", "Julien Da Costa": "ジュリアン・ダ・コスタ", "Julien Enjolras": "ジュリアン・アンジョルラ", "Jun Inageda": "イナゲダ・ジュン",
"Junzo Suzuki": "スズキ・ジュンゾウ", "Jurgen Fuchs": "ユルゲン・フックス", "K. Ohta": "オオタ・K", "Karl Truchsess": "カール・トルフゼス",
"Katsuaki Fujiwara": "フジワラ・カツアキ", "Katsuji Uezu": "ウエズ・カツジ", "Katsuyoshi Kozono": "小園勝義", "Kazuhiro Kubo": "クボ・カズヒロ",
"Kazuhiro Takao": "タカオ・カズヒロ", "Kazuto Sakata": "坂田和人", "Keiichi Kitagawa": "キタガワ・ケイイチ", "Keiichiro Iwahashi": "イワハシ・ケイイチロウ",
"Keiji Ohishi": "オオイシ・ケイジ", "Ken Eguchi": "エグチ・ケン", "Ken Fisher": "ケン・フィッシャー", "Ken Miyasaka": "ミヤサカ・ケン", "Ken Ohashi": "オオハシ・ケン",
"Kenny Tibble": "ケニー・ティブル", "Kensuke Haga": "芳賀健輔", "Kevin Curtain": "ケヴィン・カーテン", "Kevin Magee": "ケヴィン・マギー",
"Kevin Mawdsley": "ケヴィン・モーズリー", "Kevin Mitchell": "ケヴィン・ミッチェル", "Kevin Murray": "ケヴィン・マレー", "Kevin Schwantz": "ケビン・シュワンツ",
"Kinya Wada": "ワダ・キンヤ", "Kirk McCarthy": "カーク・マッカーシー", "Koji Takada": "タカダ・コウジ", "Krisse Kaas": "クリッセ・カース",
"Meng Heng Kuan": "メン・ヘン・クアン", "Kunihiro Amano": "アマノ・クニヒロ", "Kunio Machii": "町井邦生", "Kyoji Nanba": "難波恭司", "Lars Langer": "ラース・ランガー",
"Laszlo Bancsiki": "ラースロー・バンチキ", "Laurent Naveau": "ローラン・ナヴォー", "Leandro Giuggia": "レアンドロ・ジュッジャ", "Leandro Mulet": "レアンドロ・ムレ",
"Leandro Panadés": "レアンドロ・パナデス", "Lee Jackson": "リー・ジャクソン", "Lee Pullan": "リー・プラン", "Leon Van Der Heyden": "レオン・ファン・デル・ハイデン",
"Linda Walsh": "リンダ・ウォルシュ", "Loek Bodelier": "ルーク・ボデリエ", "Lorenzo Lanzi": "ロレンツォ・ランツィ", "Loris Reggiani": "ロリス・レジアーニ",
"Lothar Neukirchner": "ロタール・ノイキルヒナー", "Luca Boscoscuro": "ルカ・ボスコスクーロ", "Luca Cadalora": "ルカ・カダローラ", "Lucas Oliver": "ルーカス・オリベル",
"Lucio Pedercini": "ルーチョ・ペデルチーニ", "Luigi Ancona": "ルイジ・アンコーナ", "Luis Alvaro": "ルイス・アルバロ", "Luis Carlos Maurel": "ルイス・カルロス・マウレル",
"Luis Costa": "ルイス・コスタ", "Luis D'Antin": "ルイス・ダンティン", "Luis Miguel Reyes": "ルイス・ミゲル・レジェス", "M. Meganathan": "M・メガナタン",
"M. Yamagishi": "ヤマギシ・M", "Maik Stief": "マイク・シュティーフ", "Malcolm Yeo": "マルコム・ヨー", "Manfred Baumann": "マンフレート・バウマン",
"Manfred Geissler": "マンフレート・ガイスラー", "Manie Maritz": "マニー・マリッツ", "Manuel Herreros": "マヌエル・エレロス", "Manuel Luque": "マヌエル・ルケ",
"Marc Garcia": "マルク・ガルシア", "Marcel Nooren": "マルセル・ノーレン", "Marcel Schneider": "マルセル・シュナイダー", "Marco Borciani": "マルコ・ボルチャーニ",
"Marco Masetti": "マルコ・マゼッティ", "Marco Papa": "マルコ・パーパ", "Marco Tresoldi": "マルコ・トレゾルディ", "Marcos Cativa Tolos": "マルコス・カティバ・トロス",
"Marcus Payten": "マーカス・ペイトン", "Marek Moravek": "マレク・モラヴェク", "Mario De Matteo": "マリオ・デ・マッテオ", "Mark Rowling": "マーク・ローリング",
"Mark Willis": "マーク・ウィリス", "Markus Barth": "マルクス・バルト", "Markus Ober": "マルクス・オーバー", "Martin Craggill": "マーティン・クラギル",
"Martin Psotny": "マルティン・プソトニー", "Martin Trösch": "マルティン・トレッシュ", "Martin Wimmer": "マルティン・ヴィマー", "Masafumi Ono": "オノ・マサフミ",
"Masaki Morikane": "モリカネ・マサキ", "Masao Shimizu": "シミズ・マサオ", "Masato Shima": "シマ・マサト", "Massimiliano D'Agnano": "マッシミリアーノ・ダニャーノ",
"Massimo Ottobre": "マッシモ・オットーブレ", "Massimo Pennacchioli": "マッシモ・ペンナッキオーリ", "Masumitsu Taguchi": "田口益充", "Mathias Neukirchen": "マティアス・ノイキルヒェン",
"Matias Rios": "マティアス・リオス", "Matt Mladin": "マット・ムラディン", "Matt Wait": "マット・ウェイト", "Matthieu Lagrive": "マチュー・ラグリーヴ",
"Mattieu van Gaalen": "マティユー・ファン・ハーレン", "Maurice Bolwerk": "マウリス・ボルウェルク", "Maurice Hawthorne": "モーリス・ホーソーン", "Maurizio Cucchiarini": "マウリツィオ・クッキアリーニ",
"Maurizio Vitali": "マウリツィオ・ヴィターリ", "Max Gambino": "マックス・ガンビーノ", "Michael Garcia": "ミカエル・ガルシア", "Michael Haisman": "マイケル・ハイスマン",
"Michael Liedl": "ミヒャエル・リードル", "Michael Rudroff": "ミヒャエル・ルドロフ", "Michael Rutter": "マイケル・ラター", "Michael Schulten": "ミヒャエル・シュルテン",
"Michael Teniswood": "マイケル・テニスウッド", "Michael Witzeneder": "ミヒャエル・ヴィッツェネーダー", "Michal Brezina": "ミハル・ブジェジナ", "Michale Herzberg": "マイケル・ハーツバーグ",
"Michele Gallina": "ミケーレ・ガッリーナ", "Michele Valdo": "ミケーレ・ヴァルド", "Mick Doohan": "ミック・ドゥーハン", "Miguel Castilla": "ミゲル・カスティーリャ",
"Miguel Tey": "ミゲル・テイ", "Mike Baldinger": "マイク・バルディンガー", "Mike Hale": "マイク・ヘイル", "Mike Leitner": "マイク・ライトナー",
"Mike Lougassi": "マイク・ルガッシ", "Mike Sullivan": "マイク・サリバン", "Mike Webb": "マイク・ウェッブ", "Mike Wilson": "マイク・ウィルソン",
"Minoru Nakamura": "ナカムラ・ミノル", "Miroslav Kacko": "ミロスラフ・カチコ", "Mokoto Ono": "オノ・マコト", "Naohiro Negishi": "ネギシ・ナオヒロ",
"Naoki Katoh": "カトウ・ナオキ", "Naoto Ogura": "オグラ・ナオト", "Niall Mackenzie": "ニール・マッケンジー", "Nicholas Schmassmann": "ニコラス・シュマスマン",
"Nick Hopkins": "ニック・ホプキンス", "Nick Ienatsch": "ニック・イエナッチ", "Nicolas Dussauge": "ニコラ・デュソージュ", "Nigel Bosworth": "ナイジェル・ボズワース",
"Nobuyuki Wakai": "若井伸之", "Nobuyuki Yunoki": "ユノキ・ノブユキ", "Noel Ferro": "ノエル・フェロ", "Norihiko Fujiwara": "藤原儀彦",
"Noriyasu Numata": "沼田憲保", "Néstor Amoroso": "ネストル・アモローソ", "Oliver Koch": "オリバー・コッホ", "Oliver Perschke": "オリバー・ペルシュケ",
"Oliver Petrucciani": "オリヴァー・ペトルッチャーニ", "Osamu Hiwatashi": "ヒワタシ・オサム", "Oscar Sainz": "オスカル・サインス", "Otto Krmicek": "オットー・クルミチェク",
"Pablo Zeballos": "パブロ・セバジョス", "Paolo Casoli": "パオロ・カゾーリ", "Paolo Tessari": "パオロ・テッサーリ", "Patrick Igoa": "パトリック・イゴア",
"Patrick van den Goorbergh": "パトリック・ファン・デン・フーアベルフ", "Paul Brown": "ポール・ブラウン", "Paul Jones": "ポール・ジョーンズ", "Paul Robinson": "ポール・ロビンソン",
"Paul Young": "ポール・ヤング", "Pete Jennings": "ピート・ジェニングス", "Peter Den Heyer": "ペーター・デン・ハイヤー", "Peter Galvin": "ピーター・ガルヴィン",
"Peter Goddard": "ピーター・ゴダード", "Peter Graves": "ピーター・グレイヴス", "Peter Koller": "ペーター・コラー", "Peter Linden": "ペーテル・リンデン",
"Peter McFayden": "ピーター・マクファイデン", "Peter Scott": "ピーター・スコット", "Peter Öttl": "ペーター・エッテル", "Petrus Canisius": "ペトルス・カニシウス",
"Phil Giles": "フィル・ジャイルズ", "Phillipp Hafeneger": "フィリップ・ハーフェネガー", "Pierfrancesco Chili": "ピエルフランチェスコ・キリ", "Pierre Monneret": "ピエール・モヌレ",
"Rachel Nicotte": "ラシェル・ニコット", "Ramón Mesa": "ラモン・メサ", "Randy Mamola": "ランディ・マモラ", "Raul Loscos": "ラウル・ロスコス",
"Reinhard Stolz": "ラインハルト・シュトルツ", "Reinhold Roth": "ラインホルト・ロート", "Renato Colleoni": "レナート・コッレオーニ", "Renato Velludo": "レナト・ヴェルード",
"Rene Bongers": "ルネ・ボンガース", "Rene Knoefler": "レネ・クネフラー", "Renzo Colleoni": "レンツォ・コッレオーニ", "René Dünki": "ルネ・デュンキ",
"Riccardo Chiarello": "リッカルド・キアレッロ", "Rich Oliver": "リッチ・オリバー", "Rick Kirk": "リック・カーク", "Rick Tripodi": "リック・トリポディ",
"Rick Van Etten": "リック・ファン・エッテン", "Ricky Rice": "リッキー・ライス", "Rob Filart": "ロブ・フィラルト", "Robbie Petersen": "ロビー・ピーターセン",
"Roberto Bellei": "ロベルト・ベッレイ", "Roberto Van Keulen": "ロベルト・ファン・クーレン", "Robin Appleyard": "ロビン・アップルヤード", "Robin Milton": "ロビン・ミルトン",
"Rodney Fee": "ロドニー・フィー", "Roger Harrison": "ロジャー・ハリソン", "Romolo Balbi": "ロモロ・バルビ", "Ron Haslam": "ロン・ハスラム", "Ron Reniers": "ロン・レニールス",
"Ronnie Timmer": "ロニー・ティマー", "Rudi Arianto": "ルディ・アリアント", "Rudie Markink": "ルディ・マルキンク", "Russell Wood": "ラッセル・ウッド",
"Sadanori Hikita": "ヒキタ・サダノリ", "Salvador Martin": "サルバドール・マルティン", "Satoshi Tsujimoto": "辻本聡", "Scott Buckley": "スコット・バックリー",
"Scott Doohan": "スコット・ドゥーハン", "Scott Gray": "スコット・グレイ", "Scott Russell": "スコット・ラッセル", "Scott Smart": "スコット・スマート",
"Sean Emmett": "ショーン・エメット", "Sebastian Scarnato": "セバスチャン・スカルナト", "Sebastien Gimbert": "セバスチャン・ジンベール", "Sebastien Legrelle": "セバスチャン・ルグレル",
"Serafino Foti": "セラフィーノ・フォーティ", "Serge David": "セルジュ・ダヴィド", "Shahrun Nizam": "シャールン・ニザム", "Shane Norval": "シェーン・ノーヴァル",
"Shane Smith": "シェーン・スミス", "Shaun Geronimi": "ショーン・ジェロニミ", "Shigeru Ibaraki": "イバラキ・シゲル", "Shinichi Sugaya": "スガヤ・シンイチ",
"Shinji Katayama": "カタヤマ・シンジ", "Silvio Cesar Zequim": "シルヴィオ・セーザル・ゼキン", "Simon Buckmaster": "サイモン・バックマスター", "Simon Crafar": "サイモン・クラファー",
"Sinya Sato": "サトウ・シンヤ", "Sito Pons": "シト・ポンス", "Stefan Brägger": "シュテファン・ブレッガー", "Stefan Dörflinger": "シュテファン・デルフリンガー",
"Stefan Kruse": "シュテファン・クルーゼ", "Stefan Kurfiss": "シュテファン・クルフィス", "Stefan Prein": "シュテファン・プライン", "Stefano Caracchi": "ステファノ・カラッキ",
"Stefano Cruciani": "ステファノ・クルチアーニ", "Stefano Pennese": "ステファノ・ペンネーゼ", "Stephen Whitehouse": "スティーヴン・ホワイトハウス", "Steve Hislop": "スティーヴ・ヒスロップ",
"Steve Manley": "スティーヴ・マンリー", "Steve Martin": "スティーヴ・マーティン", "Steve Patrickson": "スティーヴ・パトリクソン", "Steve Sawford": "スティーヴ・ソーフォード",
"Steve Spray": "スティーヴ・スプレイ", "Stuart Easton": "スチュアート・イーストン", "Stuart Edwards": "スチュアート・エドワーズ", "Stéphane Mertens": "ステファン・メルテンス",
"Tadahiko Taira": "平忠彦", "Takahito Mori": "モリ・タカヒト", "Takao Shimizu": "シミズ・タカオ", "Takashi Akita": "アキタ・タカシ", "Takayuki Onodera": "オノデラ・タカユキ",
"Takehiko Kurokawa": "クロカワ・タケヒコ", "Takeshi Tsujimura": "辻村猛", "Takuma Aoki": "青木琢磨", "Taru Rinne": "タル・リンネ", "Tasuro Arata": "アラタ・タスロウ",
"Terry Carter": "テリー・カーター", "Terry Paviell": "テリー・パヴィエル", "Terry Rymer": "テリー・ライマー", "Tetsu Ito": "イトウ・テツ", "Thierry Crine": "ティエリー・クリーヌ",
"Thierry Feuz": "ティエリー・フォイツ", "Tibor Kis": "ティボル・キシュ", "Tobias Kirmeier": "トビアス・キルマイヤー", "Tom Ouvrard": "トム・ウヴラール",
"Tom Tunstall": "トム・タンストール", "Tomas Miksovsky": "トマーシュ・ミクショフスキー", "Tomoko Igata": "イガタ・トモコ", "Tomomi Manako": "眞子智実",
"Tony Daly": "トニー・デイリー", "Tony Sims": "トニー・シムズ", "Toshi Arakaki": "アラカキ・トシ", "Toshiaki Ozawa": "オザワ・トシアキ", "Toshihiko Honma": "本間利彦",
"Toshinobu Shiomori": "シオモリ・トシノブ", "Trevor Manley": "トレヴァー・マンリー", "Troy Corser": "トロイ・コーサー", "Tsumoto Udagawa": "ウダガワ・ツモト",
"Udo Mark": "ウド・マーク", "Urs Jücker": "ウルス・ユッカー", "Uwe Bolteraurer": "ウーヴェ・ボルテラウアー", "Veng Kit Tong": "ヴェン・キット・トン",
"Vicente Esparragoso": "ビセンテ・エスパラゴソ", "Victor Carrasco": "ビクトル・カラスコ", "Vittorio Lopez": "ヴィットリオ・ロペス", "Vittorio Scatola": "ヴィットリオ・スカトーラ",
"Volker Bahr": "フォルカー・バール", "Warren Palesy": "ウォーレン・パレシー", "Wayne Gardner": "ワイン・ガードナー", "Wayne Rainey": "ウェイン・レイニー",
"Wesley Gutierrez": "ウェズリー・グティエレス", "Wilco Zeelenberg": "ウィルコ・ゼーレンベルフ", "Wilhelm Van Leeuwen": "ウィルヘルム・ファン・レーウェン", "William Costes": "ウィリアム・コステス",
"William De Angelis": "ウィリアム・デ・アンジェリス", "William Doran": "ウィリアム・ドーラン", "William Strugnell": "ウィリアム・ストラグネル", "Wolfgang Fritz": "ヴォルフガング・フリッツ",
"Woolsey Coulter": "ウールジー・コールター", "Xavier Soler": "シャビエル・ソレル", "Yasir Said": "ヤシル・サイード", "Yasu Hatakeyama": "ハタケヤマ・ヤス",
"Yasuaki Takahashi": "タカハシ・ヤスアキ", "Yau Chuen Tang": "ヤウ・チュン・タン", "Yoshiaki Katoh": "カトウ・ヨシアキ", "Yoshiari Hori": "ホリ・ヨシアリ",
"Yoshifumi Ichimiya": "イチミヤ・ヨシフミ", "Yoshinori Korogi": "コロギ・ヨシノリ", "Yoshiteru Konishi": "コニシ・ヨシテル", "Yoshiyuki Sugai": "スガイ・ヨシユキ",
"Yoshomasa Kato": "カトウ・ヨシマサ", "Yosuke Yamakawa": "ヤマカワ・ヨウスケ", "Yukiho Hinokio": "ヒノキオ・ユキホ", "Yukio Nukumi": "ヌクミ・ユキオ",
"Yutaka Fujihara": "フジハラ・ユタカ", "Yves Briguet": "イヴ・ブリゲ",
})
JA.update({
# ---- 1980〜1989年 ----
"Kenny Roberts": "ケニー・ロバーツ", "A. Gouin": "A・グワン", "A. Mayer": "A・マイヤー", "Aad Wijsman": "アート・ワイスマン", "Adelio Faccioli": "アデリオ・ファッチョーリ",
"Alain Beraud": "アラン・ベロー", "Alain Kempener": "アラン・ケンペネール", "Alain Roethlisberger": "アラン・レトリスベルガー", "Alain Trippaers": "アラン・トリパールス",
"Alan Jeffrey": "アラン・ジェフリー", "Alan Labrosse": "アラン・ラブロス", "Alan North": "アラン・ノース", "Alan Watts": "アラン・ワッツ", "Aldo Pero": "アルド・ペーロ",
"Alejandro Aleman": "アレハンドロ・アレマン", "Alessandro Valesi": "アレッサンドロ・ヴァレージ", "Alex Bedford": "アレックス・ベッドフォード", "Alex George": "アレックス・ジョージ",
"Alf Graarud": "アルフ・グラールド", "Alfons Ammerschlager": "アルフォンス・アマーシュレーガー", "Alfons Breu": "アルフォンス・ブロイ", "Alois Meyer": "アロイス・マイヤー",
"Alojz Pavlic": "アロイズ・パブリッチ", "Anders Anderson": "アンデシュ・アンデション", "Andrea Brasini": "アンドレア・ブラジーニ", "Andreas Berger": "アンドレアス・ベルガー",
"Andreas Hofmann": "アンドレアス・ホフマン", "Andreas Sanches-Marin": "アンドレアス・サンチェス＝マリン", "Andreas Woditsch": "アンドレアス・ヴォディッチュ",
"Angel Nieto": "アンヘル・ニエト", "Angel del Pozo": "アンヘル・デル・ポソ", "Antoine Longo": "アントワーヌ・ロンゴ", "Anton Berghammer": "アントン・ベルクハマー",
"Anton Mang": "アントン・マン", "Anton Straver": "アントン・ストラーフェル", "Antonio Barbosa": "アントニオ・バルボサ", "Antonio Boronat": "アントニオ・ボロナト",
"Antonio Neto": "アントニオ・ネト", "Antonio Oliveros": "アントニオ・オリベロス", "Antonio Perez": "アントニオ・ペレス", "Antoon Gevers": "アントーン・ヘフェルス",
"Armando Errico": "アルマンド・エッリコ", "Attilio Riondato": "アッティリオ・リオンダート", "August Auinger": "アウグスト・アウインガー", "August Weissner": "アウグスト・ヴァイスナー",
"B. Elgh": "B・エルグ", "Barry Kerr": "バリー・カー", "Barry Sheene": "バリー・シーン", "Barry Smith": "バリー・スミス", "Barry Woodland": "バリー・ウッドランド",
"Beat Sidler": "ベアト・ジードラー", "Bedřich Fendrich": "ベドジフ・フェンドリフ", "Bengt Eliasson": "ベングト・エリアソン", "Bengt Slydal": "ベングト・スリダル",
"Benny Mortensen": "ベニー・モーテンセン", "Bernard Andrault": "ベルナール・アンドロー", "Bernard Fau": "ベルナール・フォー", "Bernard Gitton": "ベルナール・ジトン",
"Bernd Lauermann": "ベルント・ラウアーマン", "Bernd Rossbach": "ベルント・ロスバッハ", "Bernd Völkel": "ベルント・フェルケル", "Bertus Grinwis": "ベルトゥス・フリンウィス",
"Bo Blumenthal": "ボー・ブルメンタール", "Boet Van Dulmen": "ブート・ファン・ドゥルメン", "Bogdan Nikolov": "ボグダン・ニコロフ", "Boy van Erp": "ボーイ・ファン・エルプ",
"Brane Rokavec": "ブラネ・ロカベツ", "Brent Jones": "ブレント・ジョーンズ", "Brett Hudson": "ブレット・ハドソン", "Bruno Kneubühler": "ブルーノ・クノイビューラー",
"Bruno Luscher": "ブルーノ・ルッシャー", "Bruno di Carlo": "ブリュノ・ディ・カルロ", "Bubba Shobert": "ババ・ショバート", "Børge Nielsen": "ボーエ・ニールセン",
"Cai Hedstrom": "カイ・ヘドストレム", "Carlo Perugini": "カルロ・ペルジーニ", "Carlo Succi": "カルロ・スッチ", "Carlos Morante": "カルロス・モランテ",
"Cees Besseling": "ケース・ベッセリング", "Cees Van Dongen": "ケース・ファン・ドンゲン", "Charlie Williams": "チャーリー・ウィリアムズ", "Chas Mortimer": "チャス・モーティマー",
"Chris Baert": "クリス・バールト", "Chris Buerki": "クリス・ビュルキ", "Chris Fisker": "クリス・フィスカー", "Chris Guy": "クリス・ガイ", "Chris Leah": "クリス・リー",
"Chris Martin": "クリス・マーティン", "Chris Oldfield": "クリス・オールドフィールド", "Christer Eliasson": "クリステル・エリアソン", "Christian Andrieu": "クリスチャン・アンドリュー",
"Christian Estrosi": "クリスチャン・エストロジ", "Christian Le Liard": "クリスチャン・ル・リアール", "Christoph Bürki": "クリストフ・ビュルキ", "Claude Albert": "クロード・アルベール",
"Claude Delarbre": "クロード・ドラルブル", "Claudio Granata": "クラウディオ・グラナータ", "Claudio Lusuardi": "クラウディオ・ルスアルディ", "Claudio Macciotta": "クラウディオ・マッチョッタ",
"Claus Wulff": "クラウス・ヴルフ", "Con Law": "コン・ロー", "Constant Pittet": "コンスタン・ピテ", "Corrado Tuzii": "コッラード・トゥッツィ", "Daniel Mateos": "ダニエル・マテオス",
"Danny Bristol": "ダニー・ブリストル", "Dario Casais": "ダリオ・カサイス", "Darko Keletic": "ダルコ・ケレティッチ", "Dave Emond": "デイヴ・エモンド", "Dave Estment": "デイヴ・エストメント",
"Dave Griffiths": "デイヴ・グリフィス", "Dave Leach": "デイヴ・リーチ", "Dave Petersen": "デイヴ・ピーターセン", "Dave Potter": "デイヴ・ポッター", "David Floyd Busby": "デヴィッド・フロイド・バスビー",
"David Griffith": "デヴィッド・グリフィス", "Davide Tardozzi": "ダヴィデ・タルドッツィ", "Dennis Batchelor": "デニス・バチェラー", "Dennis Ireland": "デニス・アイルランド",
"Des Barry": "デス・バリー", "Dick Alblas": "ディック・アルブラス", "Dick van Logchem": "ディック・ファン・ロッヘム", "Dieter Göppner": "ディーター・ゲップナー",
"Dietmar Mayer": "ディートマー・マイヤー", "Dimitrios Papandreou": "ディミトリオス・パパンドレウ", "Dirk Hafeneger": "ディルク・ハーフェネガー", "Domingo Gil": "ドミンゴ・ヒル",
"Dominique Pernet": "ドミニク・ペルネ", "Donald Shaw": "ドナルド・ショー", "Donnie McLeod": "ドニー・マクロード", "Donnie Robinson": "ドニー・ロビンソン",
"Drago Josipovic": "ドラゴ・ヨシポヴィッチ", "Edi Stoellinger": "エディ・シュテリンガー", "Eduardo Aleman": "エドゥアルド・アレマン", "Eduardo Amen": "エドゥアルド・アメン",
"Edward Rees": "エドワード・リース", "Edwin Weibel": "エトヴィン・ヴァイベル", "Eero Hyvarinen": "エーロ・ヒュヴァリネン", "Eico Rispens": "エイコ・リスペンス",
"Eilert Lundstedt": "エイレット・ルンドステット", "Enrico Cereda": "エンリコ・チェレーダ", "Eric Gijsel": "エリック・ハイセル", "Eric Sabatier": "エリック・サバティエ",
"Eric Saul": "エリック・ソール", "Eric de Donker": "エリック・デ・ドンケル", "Erich Klein": "エーリッヒ・クライン", "Erich Sanders": "エーリッヒ・ザンダース",
"Ernst Gschwender": "エルンスト・グシュヴェンダー", "Ernst Himmelsbach": "エルンスト・ヒンメルスバッハ", "Esa Kytölä": "エサ・キュトラ", "Etienne Geeraerd": "エティエンヌ・ヘーラールト",
"Eugene Brown": "ユージン・ブラウン", "Eugenio Lazzarini": "エウジェニオ・ラッツァリーニ", "Ezio Saffiotti": "エツィオ・サッフィオッティ", "F. Beck": "F・ベック",
"F. Marcheggiani": "F・マルケッジャーニ", "Fabio Barchitta": "ファビオ・バルキッタ", "Fabio Biliotti": "ファビオ・ビリオッティ", "Fabio Marcaccini": "ファビオ・マルカッチーニ",
"Fabio Meozzi": "ファビオ・メオッツィ", "Fabrizio Fantini": "ファブリツィオ・ファンティーニ", "Felix Rodriguez": "フェリックス・ロドリゲス", "Fernando Cerdera": "フェルナンド・セルデラ",
"Fernando Gonzalez": "フェルナンド・ゴンサレス", "Fernando González de Nicolás": "フェルナンド・ゴンサレス・デ・ニコラス", "Flemming Sorensen": "フレミング・ソレンセン",
"Francisco Gonzales": "フランシスコ・ゴンサレス", "Francisco Incorvaia": "フランシスコ・インコルバイア", "Franco Incorvaia": "フランコ・インコルバイア",
"Franco Marchegiani": "フランコ・マルケジャーニ", "Franco Uncini": "フランコ・ウンチーニ", "Frank Gross": "フランク・グロス", "Franz Birrer": "フランツ・ビラー",
"Franz Holzmeier": "フランツ・ホルツマイヤー", "Franz Kaserer": "フランツ・カゼラー", "Franz Lederer": "フランツ・レーデラー", "Franz Wagner": "フランツ・ヴァーグナー",
"Fred Merkel": "フレッド・マーケル", "Freddy Blaise": "フレディ・ブレーズ", "Fritz Kerschbaumer": "フリッツ・ケルシュバウマー", "Frédéric Michel": "フレデリック・ミシェル",
"G. Boehl": "G・ベール", "Gabriel Grabia": "ガブリエル・グラビア", "Gabriele Gnani": "ガブリエレ・ニャーニ", "Garry Cowan": "ギャリー・コーワン", "Gary Lingham": "ゲイリー・リンガム",
"Gary Noel": "ゲイリー・ノエル", "Gary Padgett": "ゲイリー・パジェット", "Gastone Grassetti": "ガストーネ・グラッセッティ", "Geir Hestman": "ゲイル・ヘストマン",
"Geoff Fowler": "ジェフ・ファウラー", "Georg-Robert Jung": "ゲオルク＝ローベルト・ユング", "George Looijesteijn": "ヘオルヘ・ローイエステイン", "Gerard Vallee": "ジェラール・ヴァレ",
"Gerard Velay": "ジェラール・ヴレ", "Gerd Kafka": "ゲルト・カフカ", "Gerhard Bauer": "ゲルハルト・バウアー", "Gerhard Treusch": "ゲルハルト・トロイシュ",
"Gerhard Vogt": "ゲルハルト・フォークト", "Gerhard Waibel": "ゲルハルト・ヴァイベル", "Gerold Fischer": "ゲロルト・フィッシャー", "Gert Bender": "ゲルト・ベンダー",
"Gianfranco Bonera": "ジャンフランコ・ボネーラ", "Gianni Pelletier": "ジャンニ・ペッレティエ", "Gianni Rolando": "ジャンニ・ロランド", "Gianpaolo Marchetti": "ジャンパオロ・マルケッティ",
"Gilles Riva": "ジル・リヴァ", "Gina Bovaird": "ジーナ・ボヴェアード", "Giuliano Gerani": "ジュリアーノ・ジェラーニ", "Giuliano Tabanelli": "ジュリアーノ・タバネッリ",
"Giuseppe Ascareggi": "ジュゼッペ・アスカレッジ", "Graeme Crosby": "グレアム・クロスビー", "Graeme McGregor": "グレアム・マクレガー", "Graham Singer": "グレアム・シンガー",
"Graham Young": "グレアム・ヤング", "Graziano Rossi": "グラツィアーノ・ロッシ", "Greame Geddes": "グレアム・ゲデス", "Greg Hansford": "グレッグ・ハンスフォード",
"Guido Paci": "グイド・パーチ", "Guido Sala": "グイド・サーラ", "Gunnar Bruhn": "グンナー・ブルーン", "Gustav Reiner": "グスタフ・ライナー", "Guy Bertin": "ギー・ベルタン",
"Guy Olla": "ギー・オラ", "Günter Schirnhofer": "ギュンター・シルンホーファー", "H. Engelhardt": "H・エンゲルハルト", "H. Lichtenberg": "H・リヒテンベルク", "H. Tomic": "H・トミッチ",
"Hagen Klein": "ハーゲン・クライン", "Hakan Olsson": "ホーカン・オルソン", "Hannu Kallio": "ハンヌ・カッリオ", "Hans Hansebraten": "ハンス・ハンセブローテン",
"Hans Hummel": "ハンス・フンメル", "Hans Klingebiel": "ハンス・クリンゲビール", "Hans Lindner": "ハンス・リントナー", "Hans Müller": "ハンス・ミュラー",
"Hans Pristavnik": "ハンス・プリスタヴニク", "Hans-Joachim Ritter": "ハンス＝ヨアヒム・リッター", "Harald Bartol": "ハラルト・バルトル", "Harald Becker": "ハラルト・ベッカー",
"Harrie Heutmekers": "ハリー・ヘウトメーケルス", "Hein Vink": "ハイン・フィンク", "Heinz Paschen": "ハインツ・パッシェン", "Helmut Lichtenburg": "ヘルムート・リヒテンブルク",
"Henk De Vries": "ヘンク・デ・フリース", "Henk Van Der Mark": "ヘンク・ファン・デル・マルク", "Henk Van Kessel": "ヘンク・ファン・ケッセル", "Henk van Schijndel": "ヘンク・ファン・スハインデル",
"Henri Laporte": "アンリ・ラポルト", "Henri van Heist": "ヘンリ・ファン・ヘイスト", "Henrik Rasmussen": "ヘンリク・ラスムセン", "Henrique Sande": "エンリケ・サンデ",
"Henry Nagel": "ヘンリー・ナーゲル", "Herbert Besendorfer": "ヘルベルト・ベゼンドルファー", "Herbert Hauf": "ヘルベルト・ハウフ", "Hermann Holder": "ヘルマン・ホルダー",
"Herve Guilleux": "エルヴェ・ギユー", "Hideshi Tomita": "トミタ・ヒデシ", "Hiroyuki Kawasaki": "カワサキ・ヒロユキ", "Hisashi Yamana": "ヤマナ・ヒサシ",
"Horst Elsenheimer": "ホルスト・エルゼンハイマー", "Horst Seel": "ホルスト・ゼール", "Hubert Genoud": "ユベール・ジュヌー", "Hubert Rigal": "ユベール・リガル",
"Hugo Vignetti": "ウーゴ・ヴィニェッティ", "Ian Pratt": "イアン・プラット", "Ian Saunders": "イアン・ソーンダース", "Ikujiro Takai": "高井幾次郎", "Ilkka Jaakkola": "イルッカ・ヤーッコラ",
"Inge Arends": "インゲ・アーレンズ", "Ingo Emmerich": "インゴ・エメリッヒ", "Ivan Palazzese": "イバン・パラッツェーゼ", "Ivan Troisi": "イバン・トロイシ", "Ivan Villini": "イヴァン・ヴィッリーニ",
"J. Genoud": "J・ジュヌー", "Jack Middelburg": "ジャック・ミデルブルフ", "Jacky Onda": "ジャッキー・オンダ", "Jacques Agopian": "ジャック・アゴピアン", "Jacques Bernard": "ジャック・ベルナール",
"Jacques Bolle": "ジャック・ボル", "Jacques Grandjean": "ジャック・グランジャン", "Jacques Hutteau": "ジャック・ユトー", "Jaime Bustamante": "ハイメ・ブスタマンテ",
"Jakob Manser": "ヤコブ・マンザー", "Jamie Lodge": "ジェイミー・ロッジ", "Jan Bäckström": "ヤン・ベックストレム", "Jan Eggens": "ヤン・エッヘンス", "Jan Huberts": "ヤン・ヒューベルツ",
"Jan-Olof Odeholm": "ヤン＝オロフ・オーデホルム", "Janos Drapal": "ヤーノシュ・ドラパール", "Janos Szabo": "ヤーノシュ・サボー", "Jarmo Liitia": "ヤルモ・リーティア",
"Jarmo Piepponen": "ヤルモ・ピエッポネン", "Jean D'Assonville": "ジャン・ダソンヴィル", "Jean Francois Baldé": "ジャン＝フランソワ・バルデ", "Jean Lafond": "ジャン・ラフォン",
"Jean Louis Guignabodet": "ジャン＝ルイ・ギニャボデ", "Jean Louis Tournadre": "ジャン＝ルイ・トゥルナドル", "Jean Luc Demierre": "ジャン＝リュック・ドミエール",
"Jean Marc Toffolo": "ジャン＝マルク・トッフォロ", "Jean Michel Mattioli": "ジャン＝ミシェル・マティオリ", "Jean-Claude Collard": "ジャン＝クロード・コラール",
"Jean-Francois Verdier": "ジャン＝フランソワ・ヴェルディエ", "Jean-Jacques Peyre": "ジャン＝ジャック・ペイル", "Jean-Luc Guillemet": "ジャン＝リュック・ギユメ",
"Jean-Marc Velay": "ジャン＝マルク・ヴレ", "Jean-Paul Lecointe": "ジャン＝ポール・ルコワント", "Jeffrey Sayle": "ジェフリー・セイル", "Jhonni Baeckstroem": "ヨニ・ベックストレム",
"Jimmy Rodger": "ジミー・ロジャー", "Joan Bolart": "ジョアン・ボラルト", "Joaquim Gali": "ジョアキム・ガリ", "Joel Benniza": "ジョエル・ベニザ", "Joey Dunlop": "ジョーイ・ダンロップ",
"Johan Ten Napel": "ヨハン・テン・ナーペル", "Johann Auer": "ヨハン・アウアー", "John Kernan": "ジョン・カーナン", "John Long": "ジョン・ロング", "John Newbold": "ジョン・ニューボールド",
"Johnny Cecotto": "ジョニー・チェコット", "Johnny Scott": "ジョニー・スコット", "Jon Ekerold": "ジョン・エケロルド", "Jorge Cabanes": "ホルヘ・カバネス", "Jorgen Ask": "ヨルゲン・アスク",
"Jose Dubon": "ホセ・ドゥボン", "Jose Luis Sosa": "ホセ・ルイス・ソサ", "Jose Moreno": "ホセ・モレノ", "Jose Saez": "ホセ・サエス", "Jose de Faveri": "ジョゼ・デ・ファヴェリ",
"Josef Bader": "ヨーゼフ・バーダー", "Josef Fischer": "ヨーゼフ・フィッシャー", "Josef Hage": "ヨーゼフ・ハーゲ", "Josef Hutter": "ヨーゼフ・フッター", "Josef Ragginger": "ヨーゼフ・ラギンガー",
"Juan Bocoy": "フアン・ボコイ", "Juan Esteve": "フアン・エステベ", "Juha Pakkanen": "ユハ・パッカネン", "Junya Arai": "アライ・ジュンヤ", "Jussi Hautaniemi": "ユッシ・ハウタニエミ",
"Jörg Seel": "イェルク・ゼール", "K. Kull": "K・クル", "Karl Dauer": "カール・ダウアー", "Karl Grässel": "カール・グレッセル", "Karl-Heinz Riegl": "カール＝ハインツ・リーグル",
"Kasimer Rapczynski": "カジミール・ラプチンスキ", "Katunori Shinozaki": "シノザキ・カツノリ", "Kazuaki Yamashita": "ヤマシタ・カズアキ", "Kazuja Yamada": "ヤマダ・カズヤ",
"Kees van der Endt": "ケース・ファン・デル・エント", "Kees van der Ven": "ケース・ファン・デル・フェン", "Keiji Kinoshita": "キノシタ・ケイジ", "Keiji Tamura": "タムラ・ケイジ",
"Keith Campbell": "キース・キャンベル", "Keith Huewen": "キース・ヒューウェン", "Kenichi Yoshida": "ヨシダ・ケンイチ", "Kenny Irons": "ケニー・アイアンズ", "Kevin Hellyer": "ケヴィン・ヘリヤー",
"Kevin Wrettom": "ケヴィン・レトム", "Kimmo Kopra": "キンモ・コプラ", "Kiyotaka Sakai": "サカイ・キヨタカ", "Kjeil Warz": "シェル・ワルツ", "Kjeld Sorensen": "シェル・ソレンセン",
"Klaus Klein": "クラウス・クライン", "Klaus-Peter Baller": "クラウス＝ペーター・バラー", "Konrad Hefele": "コンラート・ヘーフェレ", "Kork Ballington": "コーク・バリントン",
"Kris Galatowicz": "クリス・ガラトヴィッツ", "Károly Juhász": "カーロイ・ユハース", "Ladislav Polák": "ラジスラフ・ポラーク", "Lajos Horti": "ラヨシュ・ホルティ",
"Larry Moreno Vacondio": "ラリー・モレノ・バコンディオ", "Lars Johansson": "ラーシュ・ヨハンソン", "Lars-Erik Kallesö": "ラーシュ＝エリク・カレセー", "Leandro Becheroni": "レアンドロ・ベケローニ",
"Leif Nielsen": "レイフ・ニールセン", "Lennart Bäckström": "レンナート・ベックストレム", "Leonard Dibon": "レナード・ディボン", "Libero Piccirillo": "リベロ・ピッチリッロ",
"Lionel Robert": "リオネル・ロベール", "Lorenzo Ghiselli": "ロレンツォ・ギゼッリ", "Lothar Spiegler": "ロタール・シュピーグラー", "Louis-Luc Maisto": "ルイ＝リュック・メスト",
"Luc Beugnier": "リュック・ブーニエ", "Lucio Pietroniro": "ルーチョ・ピエトロニーロ", "Luigi Piccirillo": "ルイジ・ピッチリッロ", "Luis Lavado": "ルイス・ラバド", "M. Mordenti": "M・モルデンティ",
"M. Musco": "M・ムスコ", "Maarten Duyzers": "マールテン・ダイゼルス", "Malcolm Campbell": "マルコム・キャンベル", "Manfred Braun": "マンフレート・ブラウン", "Manfred Fischer": "マンフレート・フィッシャー",
"Manfred Herweh": "マンフレート・ヘルヴェー", "Manfred Obinger": "マンフレート・オビンガー", "Marc Fontan": "マルク・フォンタン", "Marc Schouten": "マルク・スハウテン",
"Marcello Iannetta": "マルチェッロ・イアンネッタ", "Marco Gentile": "マルコ・ジェンティーレ", "Marco Greco": "マルコ・グレコ", "Marco Lucchinelli": "マルコ・ルッキネリ",
"Marco Marchesani": "マルコ・マルケザーニ", "Marijan Kosic": "マリヤン・コシッチ", "Marino Neri": "マリーノ・ネーリ", "Mario Rademeyer": "マリオ・ラデマイヤー", "Mark Ordridge": "マーク・オードリッジ",
"Mark Phillips": "マーク・フィリップス", "Mark Salle": "マーク・サール", "Markku Matikainen": "マルック・マティカイネン", "Martin Fug": "マルティン・フーク", "Martin van Soest": "マルティン・ファン・スースト",
"Masahiro Shimizu": "シミズ・マサヒロ", "Masaru Kobayashi": "コバヤシ・マサル", "Masaru Mizutani": "ミズタニ・マサル", "Masayuki Hirose": "ヒロセ・マサユキ", "Massimo Broccoli": "マッシモ・ブロッコリ",
"Massimo De Lorenzi": "マッシモ・デ・ロレンツィ", "Massimo Fargeri": "マッシモ・ファルジェーリ", "Massimo Matteoni": "マッシモ・マッテオーニ", "Massimo Messere": "マッシモ・メッセーレ",
"Mathias Ehinger": "マティアス・エーインガー", "Matti Kinnunen": "マッティ・キンヌネン", "Maurizio Massimiani": "マウリツィオ・マッシミアーニ", "Maurizio Stocco": "マウリツィオ・ストッコ",
"Max Wiener": "マックス・ヴィーナー", "Michael Dowson": "マイケル・ダウソン", "Michael Gschwender": "ミヒャエル・グシュヴェンダー", "Michael Jansberg": "ミカエル・ヤンスベリ",
"Michael Lederer": "ミヒャエル・レーデラー", "Michael McGarrity": "マイケル・マクギャリティ", "Michael Schmid": "ミヒャエル・シュミート", "Michel Augizeau": "ミシェル・オジゾー",
"Michel De Poligny": "ミシェル・ド・ポリニー", "Michel Escudier": "ミシェル・エスキュディエ", "Michel Frutschi": "ミシェル・フルッチ", "Michel Galbit": "ミシェル・ガルビ",
"Michel Rougerie": "ミシェル・ルジュリー", "Michel Simeon": "ミシェル・シメオン", "Michele Ettore": "ミケーレ・エットーレ", "Mick Grant": "ミック・グラント", "Mickel Nielsen": "ミッケル・ニールセン",
"Miguel Gonzales": "ミゲル・ゴンサレス", "Miguel Gugliara": "ミゲル・グリアラ", "Mijo Lijsak": "ミヨ・リシャク", "Mika-Sakari Komu": "ミカ＝サカリ・コム", "Mike Baldwin": "マイク・ボールドウィン",
"Miklos Bojan": "ミクロシュ・ボヤン", "Mile Pajic": "ミレ・パイッチ", "Miljenko Nervo": "ミリェンコ・ネルヴォ", "Mogens Johansen": "モーエンス・ヨハンセン", "N. Gatti": "N・ガッティ",
"Nardone": "ナルドーネ", "Neil Robinson": "ニール・ロビンソン", "Nicola Casadei": "ニコラ・カサデイ", "Norbert Peschke": "ノルベルト・ペシュケ", "Olivier Liégeois": "オリヴィエ・リエジョワ",
"Oscar La Ferla": "オスカル・ラ・フェルラ", "Oscar Recouso": "オスカル・レコウソ", "Otto Machinek": "オットー・マヒネク", "P. Herouard": "P・エルアール", "P. Kambourian": "P・カンブリアン",
"P. Verbic": "P・ヴェルビッチ", "Pablo Gamberini": "パブロ・ガンベリーニ", "Paolo Cipriani": "パオロ・チプリアーニ", "Paolo Ferretti": "パオロ・フェッレッティ", "Paolo Priori": "パオロ・プリオーリ",
"Pascal Seguela": "パスカル・セゲラ", "Pasquale Buonfante": "パスクワーレ・ブオンファンテ", "Patrick Chatelet": "パトリック・シャトレ", "Patrick Daudier": "パトリック・ドーディエ",
"Patrick Fernandez": "パトリック・フェルナンデス", "Patrick Gross": "パトリック・グロス", "Patrick Lagrive": "パトリック・ラグリーヴ", "Patrick Leruste": "パトリック・ルリュスト",
"Patrick Pons": "パトリック・ポンス", "Patrick Salles": "パトリック・サル", "Patrick Schmalz": "パトリック・シュマルツ", "Paul Bordes": "ポール・ボルド", "Paul Harris": "ポール・ハリス",
"Paul Iddon": "ポール・イドン", "Paul Lewis": "ポール・ルイス", "Paul Ramon": "ポール・ラモン", "Paul Rimmelzwaan": "パウル・リンメルツワーン", "Paul Tinkler": "ポール・ティンクラー",
"Pauli Freudenlund": "パウリ・フロイデンルント", "Pavol Dekánek": "パヴォル・デカーネク", "Pekka Nurmi": "ペッカ・ヌルミ", "Per Edward Carlsson": "ペール・エドヴァルド・カールソン",
"Per Larsen": "ペア・ラーセン", "Pete Wild": "ピート・ワイルド", "Peter Balaz": "ペテル・バラーシュ", "Peter Hubbard": "ピーター・ハバード", "Peter Huber": "ペーター・フーバー",
"Peter Karlsson": "ペーテル・カールソン", "Peter Lemstra": "ペーター・レムストラ", "Peter Looijesteijn": "ペーター・ローイエステイン", "Peter Schleef": "ペーター・シュレーフ",
"Peter Sjostrom": "ペーテル・ショーストレム", "Peter Sköld": "ペーテル・シェルド", "Peter Sommer": "ペーター・ゾマー", "Peter van Niel": "ペーター・ファン・ニール",
"Petri Vourela": "ペトリ・ヴォウレラ", "Phil Mellor": "フィル・メラー", "Philippe Coulon": "フィリップ・クーロン", "Philippe Linares": "フィリップ・リナレス", "Philippe Pagano": "フィリップ・パガーノ",
"Philippe Robinet": "フィリップ・ロビネ", "Philippe Robles": "フィリップ・ロブレス", "Pier Luigi Conforti": "ピエル・ルイジ・コンフォルティ", "Pier Paolo Bianchi": "ピエル・パオロ・ビアンキ",
"Pierluigi Aldrovandi": "ピエルルイジ・アルドロヴァンディ", "Pierre Bolle": "ピエール・ボル", "Pierre Tocco": "ピエール・トッコ", "Pierre-Etienne Samin": "ピエール＝エティエンヌ・サマン",
"R. Cornelis": "R・コルネリス", "R. Eskelinen": "R・エスケリネン", "R. Ruosi": "R・ルオージ", "R. Schlachter": "R・シュラクター", "R. Sibille": "R・シビーユ",
"Radovan Stanojevic": "ラドヴァン・スタノイェヴィッチ", "Rafaelle Pasqual": "ラファエレ・パスクアル", "Raimo Lipponen": "ライモ・リッポネン", "Rainer Sautter": "ライナー・ザウター",
"Rainer Scheidhauer": "ライナー・シャイトハウアー", "Rajko Mitrovic": "ライコ・ミトロヴィッチ", "Ralf Hobl": "ラルフ・ホーブル", "Ramon Gali": "ラモン・ガリ", "Ramon Pano": "ラモン・パノ",
"Randy Renfrow": "ランディ・レンフロー", "Ray Swann": "レイ・スワン", "Raymond Roche": "レイモン・ロッシュ", "Reiner Koster": "ライナー・ケスター", "Reinhard Koberstein": "ラインハルト・コーベルシュタイン",
"Reinhard Scholtis": "ラインハルト・ショルティス", "Rene Deláby": "ルネ・デラビー", "René Renier": "ルネ・ルニエ", "Ricardo Blanco": "リカルド・ブランコ", "Ricardo Tormo": "リカルド・トルモ",
"Richard Bay": "リシャール・ベ", "Richard Hubin": "リシャール・ユバン", "Richard Scott": "リチャード・スコット", "Rini Vrijdag": "リニ・フレイダッハ", "Rino Zuliani": "リーノ・ズリアーニ",
"Risto Korhonen": "リスト・コルホネン", "Rob McElnea": "ロブ・マケルニア", "Rob Punt": "ロブ・プント", "Robert Hmeljak": "ロベルト・フメリャク", "Roberto Pietri": "ロベルト・ピエトリ",
"Roberto Rosso": "ロベルト・ロッソ", "Roberto Sassone": "ロベルト・サッソーネ", "Roel Toornstra": "ルール・トールンストラ", "Roger Burnett": "ロジャー・バーネット", "Roger Marshall": "ロジャー・マーシャル",
"Roland Busch": "ローラント・ブッシュ", "Roland Freymond": "ロラン・フレイモン", "Rolf Blatter": "ロルフ・ブラッター", "Rolf Rüttimann": "ロルフ・リュッティマン", "Ronan Schulz": "ロナン・シュルツ",
"Roy Leslie": "ロイ・レスリー", "Rudolf Kunz": "ルドルフ・クンツ", "Rudolf Zeller": "ルドルフ・ツェラー", "Rune Zalle": "ルーネ・サッレ", "S. Janssen": "S・ヤンセン", "Sadao Asami": "アサミ・サダオ",
"Salvatore Milano": "サルヴァトーレ・ミラーノ", "Sandro de Rosa": "サンドロ・デ・ローザ", "Sauro Pazzaglia": "サウロ・パッツァーリア", "Seigo Kikuchi": "キクチ・セイゴ", "Seppo Korhonen": "セッポ・コルホネン",
"Seppo Rossi": "セッポ・ロッシ", "Serge Julin": "セルジュ・ジュラン", "Sergio Granton": "セルヒオ・グラントン", "Sergio Pellandini": "セルジオ・ペッランディーニ", "Shinichi Fujiyama": "フジヤマ・シンイチ",
"Shunji Yatsushiro": "八代俊二", "Siegfried Minich": "ジークフリート・ミニッヒ", "Silvio Habat": "シルヴィオ・ハバト", "Simone Crespi": "シモーネ・クレスピ", "Spencer Crabbe": "スペンサー・クラブ",
"Stefan Danielsson": "ステファン・ダニエルソン", "Stefan Förtsch": "シュテファン・フェルチュ", "Stefan Jannsen": "シュテファン・ヤンセン", "Stefan Klabacher": "シュテファン・クラバッハー",
"Stefan Sand": "ステファン・サンド", "Stefan Schmitt": "シュテファン・シュミット", "Steve Mason": "スティーヴ・メイソン", "Steve Parrish": "スティーヴ・パリッシュ", "Steve Tonkin": "スティーヴ・トンキン",
"Steve Williams": "スティーヴ・ウィリアムズ", "Steve Wright": "スティーヴ・ライト", "Stewart Cole": "スチュワート・コール", "Stuart Avant": "スチュアート・アヴァント",
"Svend Andersen": "スヴェン・アンデルセン", "T. Persic": "T・ペルシッチ", "Tadasu Ikeda": "イケダ・タダス", "Takazumi Katayama": "片山敬済", "Takumi Ito": "イトウ・タクミ",
"Teruo Fukuda": "フクダ・テルオ", "Theo Timmer": "テオ・ティマー", "Thierry Espié": "ティエリー・エスピエ", "Thierry Noblesse": "ティエリー・ノブレス", "Thierry Rapicault": "ティエリー・ラピコー",
"Thomas Bacher": "トーマス・バッハー", "Thomas Engl": "トーマス・エングル", "Thomas Møller-Pedersen": "トーマス・メラー＝ペデルセン", "Thomas Pedersen": "トーマス・ペデルセン",
"Thomas Weickardt": "トーマス・ヴァイカルト", "Timo Paavilainen": "ティモ・パーヴィライネン", "Timo Pohjola": "ティモ・ポホヨラ", "Tom Drury": "トム・ドルーリー", "Ton Spek": "トン・スペック",
"Toni Garcia": "トニ・ガルシア", "Toni Moran": "トニー・モラン", "Tony Carey": "トニー・キャリー", "Tony Head": "トニー・ヘッド", "Tony Rogers": "トニー・ロジャース", "Tony Smith": "トニー・スミス",
"Torbjorn Bastiansen": "トルビョルン・バスティアンセン", "Tore Alexandersson": "トーレ・アレクサンデション", "Trevor Nation": "トレヴァー・ネイション", "Uli Merz": "ウリ・メルツ",
"Ulrich Lang": "ウルリッヒ・ラング", "Uros Tomanovic": "ウロシュ・トマノヴィッチ", "Urs Lüzi": "ウルス・リュッツィ", "Victor Palomo": "ビクトル・パロモ", "Victorio Minguzzi": "ビクトリオ・ミングッツィ",
"Vincenzo Cascino": "ビンセンソ・カスシーノ", "Vincenzo Sblendorio": "ヴィンチェンツォ・スブレンドリオ", "Virginio Ferrari": "ヴィルジニオ・フェラーリ", "Vittorio Gibertini": "ヴィットリオ・ジベルティーニ",
"Walter Migliorati": "ヴァルテル・ミリオラーティ", "Walter Villa": "ヴァルテル・ヴィッラ", "Warren Bristol": "ウォーレン・ブリストル", "Werner Nenning": "ヴェルナー・ネニング",
"Werner Schmied": "ヴェルナー・シュミート", "Wil Hartog": "ウィル・ハルトッホ", "Wilhelm Lucke": "ヴィルヘルム・ルッケ", "Willem Heykoop": "ウィレム・ヘイコープ", "Willem Zoet": "ウィレム・ズート",
"Willi Hupperich": "ヴィリ・フッペリッヒ", "Willy Perez": "ウィリー・ペレス", "Wim Heykamp": "ウィム・ヘイカンプ", "Wim de Jong": "ウィム・デ・ヨング", "Wolfgang Glawaty": "ヴォルフガング・グラヴァティ",
"Wolfgang Müller": "ヴォルフガング・ミュラー", "Wolfgang Schwarz": "ヴォルフガング・シュヴァルツ", "Wolfgang Von Muralt": "ヴォルフガング・フォン・ムラルト", "Xavier Arumi": "シャビエル・アルミ",
"Xavier Cardelus": "シャビエル・カルデルス", "Y. Dupont": "Y・デュポン", "Yashuhiko Gomibuchi": "ゴミブチ・ヤスヒコ", "Youichi Yamamoto": "ヤマモト・ヨウイチ", "Yutaka Fujiwara": "フジワラ・ユタカ",
"Yves le Toumelin": "イヴ・ル・トゥムラン", "Z. Ljeljak": "Z・リェリャク", "Zbyněk Havrda": "ズビニェク・ハヴルダ", "Zdravko Matulja": "ズドラフコ・マトゥリャ", "Zlatko Adamovic": "ズラトコ・アダモヴィッチ",
"Maurice Coq": "モーリス・コック", "Åke Grahn": "オーケ・グラーン",
})
JA.update({"Henry Boerman": "ヘンリー・ブールマン", "Brian Lee": "ブライアン・リー", "Fabian Gonzales": "ファビアン・ゴンサレス", "Karl-Thomas Grassel": "カール＝トーマス・グレッセル", "Gerhard Singer": "ゲルハルト・ジンガー"})
JA.update({
# ---- 1970〜1979年 ----
"A. Bertholet": "A・ベルトレ", "A. Hockley": "A・ホックリー", "A. Huber": "A・フーバー", "A. Jeva": "A・イエーヴァ", "A. Kroon": "A・クローン", "A. Piccioni": "A・ピッチョーニ",
"A. Valster": "A・ファルスター", "A. Van Den Broecke": "A・ファン・デン・ブルーケ", "A. Van Der Draay": "A・ファン・デル・ドラーイ", "A. Weiss": "A・ヴァイス", "A.J. Smith": "A.J.・スミス",
"Aad Droog": "アート・ドローフ", "Aalt Toersen": "アールト・トゥールセン", "Abe Alexander": "エイブ・アレクサンダー", "Adolf Ohligschlaeger": "アドルフ・オーリヒシュレーガー",
"Adriano Cocchi": "アドリアーノ・コッキ", "Adrijan Bernetic": "アドリヤン・ベルネティッチ", "Adu Celso-Santos": "アドゥ・セルソ＝サントス", "Akihiko Kiyohara": "キヨハラ・アキヒコ",
"Alan Barnett": "アラン・バーネット", "Alan Stewart": "アラン・スチュワート", "Alberto Ieva": "アルベルト・イエーヴァ", "Alberto Pagani": "アルベルト・パガーニ",
"Aldo Nannini": "アルド・ナンニーニ", "Alfred Heck": "アルフレート・ヘック", "Alois Maxwald": "アロイス・マックスヴァルト", "Andre Luc Appietto": "アンドレ＝リュック・アピエト",
"Andre Nuno": "アンドレ・ヌーノ", "Andre Pogolotti": "アンドレ・ポゴロッティ", "André Millard": "アンドレ・ミラール", "Andy Morris": "アンディ・モリス", "Angelo Bergamonti": "アンジェロ・ベルガモンティ",
"Anssi Resko": "アンッシ・レスコ", "Aramir Brito": "アラミル・ブリト", "Armando Toracca": "アルマンド・トラッカ", "Arnold Jones": "アーノルド・ジョーンズ", "Arnulf Teuchert": "アルヌルフ・トイヒェルト",
"Arpad Juhos": "アールパード・ユホシュ", "Auno Hakala": "アウノ・ハカラ", "B. Cretti": "B・クレッティ", "B. Johansson": "B・ヨハンソン", "B. Lee": "B・リー", "B. Rossel": "B・ロッセル",
"B. Stopp": "B・シュトップ", "B. Wilbers": "B・ウィルベルス", "Barry Ditchburn": "バリー・ディッチバーン", "Barry Randle": "バリー・ランドル", "Bela Godany": "ベーラ・ゴダーニ",
"Benito Jull": "ベニート・フル", "Benjamin Grau": "ベンハミン・グラウ", "Benny Janssen": "ベニー・ヤンセン", "Bernd Köhlar": "ベルント・ケーラー", "Bernd Tungethal": "ベルント・トゥンゲタール",
"Bert Mijland": "ベルト・メイラント", "Bill Henderson": "ビル・ヘンダーソン", "Bill Rae": "ビル・レイ", "Bill Smith": "ビル・スミス", "Billie Guthrie": "ビリー・ガスリー",
"Billie Nelson": "ビリー・ネルソン", "Billy McCosh": "ビリー・マッコッシュ", "Bjorn Hasli": "ビョルン・ハスリ", "Bo Brolin": "ボー・ブローリン", "Bo Granath": "ボー・グラナート",
"Bob Coulter": "ボブ・コールター", "Bob Ware": "ボブ・ウェア", "Borje Jansson": "ボリエ・ヤンソン", "Brian Adams": "ブライアン・アダムズ", "Brian Steenson": "ブライアン・スティーンソン",
"Brian Warburton": "ブライアン・ウォーバートン", "Bruno Spaggiari": "ブルーノ・スパッジャーリ", "Börge Andersson": "ボリエ・アンデション", "C. Bellon": "C・ベロン", "C. Dumont": "C・デュモン",
"C. Geary": "C・ギアリー", "C. Guerrini": "C・グエッリーニ", "C.M. Walpole": "C.M.・ウォルポール", "CH Huguet": "C.H.・ユゲ", "Carl Ward": "カール・ウォード", "Carlo Marelli": "カルロ・マレッリ",
"Charlie Dobson": "チャーリー・ドブソン", "Charlie Sanby": "チャーリー・サンビー", "Chris Neve": "クリス・ニーヴ", "Chris Taylor": "クリス・テイラー", "Christian Bourgeois": "クリスチャン・ブルジョワ",
"Christian Leon": "クリスチャン・レオン", "Christian Ravel": "クリスチャン・ラヴェル", "Claudio Loigo": "クラウディオ・ロイゴ", "Cliff Carr": "クリフ・カー", "Clive Brown": "クライヴ・ブラウン",
"Clive Padgett": "クライヴ・パジェット", "D. Boulom": "D・ブロム", "D. Clancy": "D・クランシー", "D. Priori": "D・プリオーリ", "Daniel Corvi": "ダニエル・コルヴィ", "Dave Hughes": "デイヴ・ヒューズ",
"Dave Simmonds": "デイヴ・シモンズ", "Dennis Casement": "デニス・ケースメント", "Dennis Gallagner": "デニス・ギャラガー", "Derek Chatterton": "デレク・チャタートン", "Derek Lee": "デレク・リー",
"Dieter Braun": "ディーター・ブラウン", "Dieter Heinen": "ディーター・ハイネン", "Duilio Agostini": "ドゥイリオ・アゴスティーニ", "E. Borisenko": "E・ボリセンコ", "E. Elias": "E・エリアス",
"E. Fagerer": "E・ファーゲラー", "E. Holzeis": "E・ホルツアイス", "E. Mischiatti": "E・ミスキアッティ", "E. Saffioti": "E・サッフィオッティ", "Eddie Grant": "エディ・グラント",
"Eddie Roberts": "エディ・ロバーツ", "Edmar Ferreira": "エドマール・フェレイラ", "Edmund Czihak": "エドムント・チハク", "Egid Schwemmer": "エギト・シュヴェマー", "Emanuele Maugliani": "エマヌエーレ・マウリアーニ",
"Engelbert Kip": "エンゲルベルト・キップ", "Erick Offenstadt": "エリック・オッフェンシュタット", "Ermanno Giuliano": "エルマンノ・ジュリアーノ", "Ernie Johnson": "アーニー・ジョンソン",
"Ernst Hiller": "エルンスト・ヒラー", "Etienne Delamarre": "エティエンヌ・ドラマール", "F. Ringhini": "F・リンギーニ", "F. Van Der Hoeven": "F・ファン・デル・フーフェン", "F.V. Henderson": "F.V.・ヘンダーソン",
"Felice Agostini": "フェリーチェ・アゴスティーニ", "Fosco Giansanti": "フォスコ・ジャンサンティ", "Francesco Villa": "フランチェスコ・ヴィッラ", "Francis Holleberg": "フランシス・ホレベルグ",
"Franco Bonera": "フランコ・ボネーラ", "Francois Granon": "フランソワ・グラノン", "Frank Perris": "フランク・ペリス", "Frantisek Srna": "フランチシェク・スルナ", "Franz Heller": "フランツ・ヘラー",
"Franz Kroon": "フランツ・クローン", "Franz Rau": "フランツ・ラウ", "Franz Weidacher": "フランツ・ヴァイダッハー", "Fred Launchbury": "フレッド・ローンチベリー", "Fred Smart": "フレッド・スマート",
"Fred Stevens": "フレッド・スティーヴンス", "Fred Walton": "フレッド・ウォルトン", "Friedhelm Kohlar": "フリートヘルム・コーラー", "Fritz Reitmaier": "フリッツ・ライトマイヤー", "G. Debrok": "G・デブロック",
"G. Elementi": "G・エレメンティ", "G. Forderer": "G・フェルデラー", "G. Hilbig": "G・ヒルビッヒ", "G. Schwemmer": "G・シュヴェマー", "G. Weser": "G・ヴェーザー", "G. Willi": "G・ウィリ",
"Geoff Barry": "ジェフ・バリー", "Georg Pohlmann": "ゲオルク・ポールマン", "George Fogarty": "ジョージ・フォガティ", "Gerard Choukroun": "ジェラール・シュクルン", "Gerhard Schweikardt": "ゲルハルト・シュヴァイカルト",
"Gerhard Thurow": "ゲルハルト・トゥーロウ", "Germano Zanetti": "ジェルマーノ・ザネッティ", "Gerrit Strikker": "ヘリット・ストリッケル", "Gerry Mateer": "ジェリー・マティアー", "Getulio Marcasini": "ジェトゥリオ・マルカジーニ",
"Geza Repitz": "ゲーザ・レピツ", "Giacomo Agostini": "ジャコモ・アゴスチーニ", "Giampiero Zubani": "ジャンピエロ・ズバーニ", "Gianni Ribuffo": "ジャンニ・リブッフォ", "Gilberto Parlotti": "ジルベルト・パルロッティ",
"Ginger Molloy": "ジンジャー・モロイ", "Giovanni Buffarello": "ジョヴァンニ・ブッファレッロ", "Giovanni Perrone": "ジョヴァンニ・ペッローネ", "Giovanni Proni": "ジョヴァンニ・プローニ",
"Giuseppe Consalvi": "ジュゼッペ・コンサルヴィ", "Giuseppe Mandolini": "ジュゼッペ・マンドリーニ", "Giuseppe Mongardi": "ジュゼッペ・モンガルディ", "Giuseppe Visenzi": "ジュゼッペ・ヴィゼンツィ",
"Giuseppe Zigiotto": "ジュゼッペ・ジジョット", "Godfrey Nash": "ゴドフリー・ナッシュ", "Gordon Keith": "ゴードン・キース", "Gordon Pantall": "ゴードン・パントール", "Gosta Jensen": "ヨスタ・イェンセン",
"Graham Bailey": "グレアム・ベイリー", "Grahan Penny": "グレアム・ペニー", "Guido Mandracci": "グイド・マンドラッチ", "Gunter Bartusch": "ギュンター・バルトゥシュ", "Gunter Fischer": "ギュンター・フィッシャー",
"Guy Cooremans": "ギー・コーレマンス", "Gyula Marsovszky": "ジュラ・マルショフスキー", "H. Bartold": "H・バルトルト", "H. Gorgen": "H・ゲルゲン", "H. Heer": "H・ヘール", "H. Kittler": "H・キットラー",
"H. Konschok": "H・コンショク", "H. Kroismayr": "H・クロイスマイヤー", "H. Kuparinnen": "H・クパリネン", "Hans Bischoff": "ハンス・ビショフ", "Hans Braumandl": "ハンス・ブラウマンドル",
"Hans Dittberner": "ハンス・ディットベルナー", "Hans Hallberg": "ハンス・ハルベリ", "Hans Mühlebach": "ハンス・ミューレバッハ", "Hans Otto Butenuth": "ハンス・オットー・ブーテヌート",
"Hans Stadelmann": "ハンス・シュターデルマン", "Hans-Jürgen Rothbrust": "ハンス＝ユルゲン・ロートブルスト", "Hansrudolf Bruengger": "ハンスルドルフ・ブリュンガー", "Hanz Rosenbusch": "ハンス・ローゼンブッシュ",
"Harmunt Bischoff": "ハルトムート・ビショフ", "Harry Hoffman": "ハリー・ホフマン", "Heinz Kriwanek": "ハインツ・クリヴァネク", "Heinz Schmid": "ハインツ・シュミート", "Helmut Kassner": "ヘルムート・カスナー",
"Herbert Mann": "ヘルベルト・マン", "Herbert Rittberger": "ヘルベルト・リットベルガー", "Hermann Meyer": "ヘルマン・マイヤー", "Hideo Kanaya": "金谷秀夫", "Horst Dzierzawa": "ホルスト・ジェルザヴァ",
"Horst Kassner": "ホルスト・カスナー", "Horst Lahfeld": "ホルスト・ラーフェルト", "Hugh Evans": "ヒュー・エヴァンズ", "Ian Richards": "イアン・リチャーズ", "Ingermar Larssen": "インゲマル・ラーション",
"Ingo Koeppe": "インゴ・ケッペ", "Ivan Carlsson": "イヴァン・カールソン", "Ivan Hodgkinson": "イヴァン・ホジキンソン", "J. Alguersari": "J・アルグエルスアリ", "J. Kopitar": "J・コピタル",
"J. Kral": "J・クラール", "J. Lazo": "J・ラソ", "J. Mira": "J・ミラ", "J. Novarrete": "J・ナバレテ", "J. Pons": "J・ポンス", "J. Roller": "J・ローラー", "J. Svensson": "J・スヴェンソン",
"J. Taylor": "J・テイラー", "J.A. Lopez": "J.A.・ロペス", "Jack Findlay": "ジャック・フィンドレー", "Jacky Matagne": "ジャッキー・マターニュ", "James Pearson": "ジェームズ・ピアソン",
"Jan Bruins": "ヤン・ブラインス", "Jan De Vries": "ヤン・デ・フリース", "Jan Kostwinder": "ヤン・コストウィンデル", "Janos Reisz": "ヤーノシュ・ライス", "Jarno Saarinen": "ヤーノ・サーリネン",
"Jean Aureal": "ジャン・オレアル", "Jean Campiche": "ジャン・カンピッシュ", "Jean Claude Hogrel": "ジャン＝クロード・オグレル", "Jean Francois Lecureux": "ジャン＝フランソワ・レキュルー",
"Jean Louis Pasquier": "ジャン＝ルイ・パスキエ", "Jean Paul Boinet": "ジャン＝ポール・ボワネ", "Jean Paul Magnoni": "ジャン＝ポール・マニョーニ", "Jean Philippe Orban": "ジャン＝フィリップ・オルバン",
"Jeff Wade": "ジェフ・ウェイド", "Jerome Van Halter": "イェルーン・ファン・ハルテル", "Jerry Lancaster": "ジェリー・ランカスター", "Jim Ashton": "ジム・アシュトン", "Jim Curry": "ジム・カリー",
"Johann Parzer": "ヨハン・パルツァー", "Johann Zemsauer": "ヨハン・ツェムザウアー", "John Dodds": "ジョン・ドッズ", "John Kiddie": "ジョン・キディ", "John Weeden": "ジョン・ウィーデン",
"John Williams": "ジョン・ウィリアムズ", "John Woodley": "ジョン・ウッドリー", "Johnny Bengtsson": "ヨニー・ベングトソン", "Jos Schurgers": "ヨス・スフルヘルス", "Jose Medrano": "ホセ・メドラノ",
"Jose Peon": "ホセ・ペオン", "Josef Ozelt": "ヨーゼフ・オツェルト", "Juan Bordons": "フアン・ボルドンス", "Juan Pares": "フアン・パレス", "Julien Van Zeebroeck": "ジュリアン・ファン・ゼーブルック",
"Jurgen Lenk": "ユルゲン・レンク", "Jurgen Steiner": "ユルゲン・シュタイナー", "Juup Bosman": "ユープ・ボスマン", "K. Bertsch": "K・ベルチュ", "K. Gaber": "K・ガベル", "K. Gotesson": "K・ヨーテソン",
"K. Hernamdt": "K・ヘルナント", "K. Huggett": "K・ハゲット", "Kaarlo Koivuniemi": "カールロ・コイヴニエミ", "Kai Kuparinen": "カイ・クパリネン", "Karel Bojer": "カレル・ボイエル",
"Karl Auer": "カール・アウアー", "Karl Hoffmann": "カール・ホフマン", "Karl Hoppe": "カール・ホッペ", "Karl Huber": "カール・フーバー", "Keith Armstrong": "キース・アームストロング",
"Keith Turner": "キース・ターナー", "Kel Carruthers": "ケル・カラザーズ", "Ken Araoka": "荒岡健", "Ken Kay": "ケン・ケイ", "Ken Redfern": "ケン・レッドファーン", "Ken Tilley": "ケン・ティリー",
"Kenny Blake": "ケニー・ブレイク", "Kent Andersson": "ケント・アンデション", "Kevin Cowley": "ケヴィン・カウリー", "Kim Newcombe": "キム・ニューカム", "Kjell Solberg": "シェル・ソルベルグ",
"Klaus Huber": "クラウス・フーバー", "Klaus Leonhardt": "クラウス・レオンハルト", "Kurt-Harald Florin": "クルト＝ハラルト・フローリン", "Kurt-Ivan Carlsson": "クルト＝イヴァン・カールソン",
"L. Habbiche": "L・アビッシュ", "L. Persson": "L・ペーション", "L. Uhlig": "L・ウーリッヒ", "L. Vasco": "L・ヴァスコ", "Lazlo Szabo": "ラースロー・サボー", "Leif Gustafsson": "レイフ・グスタフソン",
"Leif Rosell": "レイフ・ロセル", "Leigh Notman": "リー・ノットマン", "Lennart Lindell": "レンナート・リンデル", "Lennart Lundgren": "レンナート・ルンドグレン", "Leo Commu": "レオ・コミュ",
"Les Kenny": "レス・ケニー", "Lewis Young": "ルイス・ヤング", "Lindsay Porter": "リンゼイ・ポーター", "Lothar John": "ロタール・ヨーン", "Lothar Mülbert": "ロタール・ミュルベルト",
"Luciano Schiavone": "ルチアーノ・スキアヴォーネ", "Ludwig Fassbender": "ルートヴィヒ・ファスベンダー", "Luigi Anelli": "ルイジ・アネッリ", "Luigi Richetti": "ルイジ・リケッティ", "Luigi Rinaudo": "ルイジ・リナウド",
"M. Arias": "M・アリアス", "M. Bernsee": "M・ベルンゼー", "M. Cannizzaro": "M・カンニッツァーロ", "M. Corradini": "M・コッラディーニ", "M. Garcia": "M・ガルシア", "M. Kugler": "M・クーグラー",
"M. Sayle": "M・セイル", "M. Servadio": "M・セルヴァディオ", "M. Soban": "M・ソバン", "M. Stripacuk": "M・ストリパチュク", "Malcolm Uphill": "マルコム・アップヒル",
"Marc Antoine Constantin": "マルク＝アントワーヌ・コンスタンタン", "Marcel Ankone": "マルセル・アンコーネ", "Marcelino Garcia": "マルセリノ・ガルシア", "Mario Lega": "マリオ・レーガ",
"Martin Carney": "マーティン・カーニー", "Martin Mijwaart": "マルティン・メイワールト", "Martin Sharpe": "マーティン・シャープ", "Martti Pesonen": "マルッティ・ペソネン", "Marty Lunde": "マーティ・ランディ",
"Masahiro Wada": "ワダ・マサヒロ", "Matti Salonen": "マッティ・サロネン", "Maurice Maingret": "モーリス・マングレ", "Max Weiner": "マックス・ヴァイナー", "Mick Chatterton": "ミック・チャタートン",
"Miguel Cortes": "ミゲル・コルテス", "Mike Evans": "マイク・エヴァンズ", "Mikko Hamunen": "ミッコ・ハムネン", "Morgan Radberg": "モルガン・ロードベリ", "N. Clague": "N・クレイグ", "N. Polane": "N・ポラン",
"Nico Van Der Zanden": "ニコ・ファン・デル・ザンデン", "Niel Tuxworth": "ニール・タックスワース", "Nigel Stone": "ナイジェル・ストーン", "Noel Clegg": "ノエル・クレッグ", "Olivier Chevallier": "オリヴィエ・シュヴァリエ",
"Oriol Fernandez": "オリオル・フェルナンデス", "Oronzo Memola": "オロンツォ・メモラ", "Otello Buscherini": "オテッロ・ブスケリーニ", "Otto Labitzke": "オットー・ラビツケ", "P. Cecchini": "P・チェッキーニ",
"P. Mezerhane": "P・メセルハネ", "P. Müller": "P・ミュラー", "P. Rüttjeroth": "P・リュットイェロート", "P. Seljak": "P・セリャク", "P. Herouard": "P・エルアール", "Paolo Campanelli": "パオロ・カンパネッリ",
"Paolo Isnardi": "パオロ・イズナルディ", "Paolo Pileri": "パオロ・ピレリ", "Paolo Tordi": "パオロ・トルディ", "Pat Hennen": "パット・ヘネン", "Patrick Plisson": "パトリック・プリソン",
"Paul Cott": "ポール・コット", "Paul Eickelberg": "パウル・アイケルベルク", "Paul Smart": "ポール・スマート", "Pentti Korhonen": "ペンッティ・コルホネン", "Pentti Lehtela": "ペンッティ・レヒテラ",
"Pentti Salonen": "ペンッティ・サロネン", "Percy Tait": "パーシー・テイト", "Pete Elmore": "ピート・エルモア", "Pete McKinley": "ピート・マッキンリー", "Peter Berwick": "ピーター・バーウィック",
"Peter Courtney": "ピーター・コートニー", "Peter Frohnmeyer": "ペーター・フローンマイヤー", "Peter Jones": "ピーター・ジョーンズ", "Peter Stocksiefen": "ペーター・シュトックジーフェン",
"Peter Van Der Wal": "ペーター・ファン・デル・ワル", "Peter Williams": "ピーター・ウィリアムズ", "Phil Carpenter": "フィル・カーペンター", "Phil Gurner": "フィル・ガーナー", "Phil Read": "フィル・リード",
"Philip Bouzanne": "フィリップ・ブザンヌ", "Philippe Gerard": "フィリップ・ジェラール", "Pierre Audry": "ピエール・オードリー", "Pierre Viura": "ピエール・ヴィウラ",
"Piet van den Goorbergh": "ピート・ファン・デン・フーアベルフ", "R. Bratenstein": "R・ブラーテンシュタイン", "R. Dickinson": "R・ディキンソン", "R. Duba": "R・ドゥバ", "R. Duffty": "R・ダフティ",
"R. Jimenez": "R・ヒメネス", "R. Oosting": "R・オースティング", "R. Reneir": "R・ルニエ", "R. Schuster": "R・シュスター", "R. Simpson": "R・シンプソン", "R. Tausani": "R・タウザーニ",
"R. Thiele": "R・ティーレ", "R. Watts": "R・ワッツ", "R.W. Herron": "R.W.・ヘロン", "Rafael Olavarria": "ラファエル・オラバリア", "Ramon Serrer": "ラモン・ゼラー", "Ray McCullough": "レイ・マカロー",
"Ray Pickrell": "レイ・ピクレル", "Ray Quincey": "レイ・クインシー", "Ray-John Laurent": "レイ＝ジョン・ローラン", "Raymond Ashcroft": "レイモンド・アシュクロフト", "Reiner Richter": "ライナー・リヒター",
"Reinhard Hiller": "ラインハルト・ヒラー", "Remy Hirschy": "レミ・ヒルシー", "Renzo Pasolini": "レンツォ・パゾリーニ", "Ricardo Russo": "リカルド・ルッソ", "Richard Stevens": "リチャード・スティーヴンス",
"Rino Pretelli": "リーノ・プレテッリ", "Rinus Van Kasteren": "リヌス・ファン・カステレン", "Rob Bron": "ロブ・ブロン", "Rob Noorlander": "ロブ・ノールランダー", "Robert Hackett": "ロバート・ハケット",
"Robert Laver": "ロバート・レイヴァー", "Roberto Gallina": "ロベルト・ガッリーナ", "Rodney Gould": "ロドニー・グールド", "Roger Bowler": "ロジャー・ボウラー", "Roger Nichols": "ロジャー・ニコルズ",
"Roger Sutcliffe": "ロジャー・サトクリフ", "Roland Nilsson": "ローランド・ニルソン", "Roland Olsson": "ローランド・オルソン", "Roland Rentzsch": "ローラント・レンチュ", "Rolf Minhoff": "ロルフ・ミンホフ",
"Ron Baylie": "ロン・ベイリー", "Ron Chandler": "ロン・チャンドラー", "Rudolf Weiss": "ルドルフ・ヴァイス", "Rudolph Keller": "ルドルフ・ケラー", "Ryszard Mankiewicz": "リシャルト・マンキェヴィチ",
"S. McClements": "S・マククレメンツ", "S. Monreale": "S・モンレアーレ", "Salvador Cañellas": "サルバドール・カニェリャス", "Santiago Herrero": "サンティアゴ・エレロ", "Selwyn Griffiths": "セルウィン・グリフィス",
"Seppo Kangasniemi": "セッポ・カンガスニエミ", "Sergio Baroncini": "セルジオ・バロンチーニ", "Siegfried Moehringer": "ジークフリート・メーリンガー", "Sigfried Lohmann": "ジークフリート・ローマン",
"Silvano Bertarelli": "シルヴァーノ・ベルタレッリ", "Silvio Grassetti": "シルヴィオ・グラッセッティ", "Stan Woods": "スタン・ウッズ", "Stefano Ferretti": "ステファノ・フェッレッティ",
"Steffan Liebst": "ステファン・リープスト", "Sten-Gunnar Jansson": "ステン＝グンナル・ヤンソン", "Steve Baker": "スティーヴ・ベイカー", "Steve Ellis": "スティーヴ・エリス", "Steve Machin": "スティーヴ・マシン",
"Steve Manship": "スティーヴ・マンシップ", "Steve Murray": "スティーヴ・マレー", "Steve Spencer": "スティーヴ・スペンサー", "Sven Gunnarsson": "スヴェン・グンナション", "T. Daleman": "T・ダーレマン",
"T. Henter": "T・ヘンター", "T. Kooyman": "T・コーイマン", "T. Ramaker": "T・ラーマーケル", "T. Rotter": "T・ロッター", "Tapio Virtanen": "タピオ・ヴィルタネン", "Ted Janssen": "テッド・ヤンセン",
"Terry Dennehy": "テリー・デネヒー", "Teuvo Lansivuori": "テウヴォ・レンシヴオリ", "Theo Bult": "テオ・ブルト", "Theo Lowes": "テオ・ロウズ", "Theo Van Geffen": "テオ・ファン・ヘッフェン",
"Thierry Van Der Veken": "ティエリー・ファン・デル・フェーケン", "Thomas Heuschkel": "トーマス・ホイシュケル", "Tierry Tchernine": "ティエリー・チェルニン", "Tom Dickie": "トム・ディッキー",
"Tom Herron": "トム・ヘロン", "Tom Loughridge": "トム・ラフリッジ", "Tom Waterer": "トム・ウォーターラー", "Tommy Robb": "トミー・ロブ", "Toni Gruber": "トニ・グルーバー", "Tony Jefferies": "トニー・ジェフリーズ",
"Tony Rutter": "トニー・ラッター", "Udo Kochanski": "ウド・コハンスキ", "Ulf Nilsson": "ウルフ・ニルソン", "Ulrich Graf": "ウルリッヒ・グラーフ", "V. Haeltert": "V・ハールテルト", "V. Novella": "V・ノヴェッラ",
"V. Perez Rubio": "V・ペレス・ルビオ", "Vanes Francini": "ヴァネス・フランチーニ", "Vasco Loro": "ヴァスコ・ローロ", "Victor Leon": "ビクトル・レオン", "Victor Soussan": "ヴィクター・スーサン",
"Vincent Duckett": "ヴィンセント・ダケット", "Vinicio Salmi": "ヴィニーチョ・サルミ", "W. Golembeck": "W・ゴレンベック", "W. Roesch": "W・レッシュ", "W. Stephan": "W・シュテファン", "W. Werner": "W・ヴェルナー",
"Walter Dawson": "ウォルター・ドーソン", "Walter Kaletsch": "ヴァルター・カレッチュ", "Walter Koschine": "ヴァルター・コシーネ", "Walter Rüngg": "ヴァルター・リュング", "Walter Scheimann": "ヴァルター・シャイマン",
"Walter Sommer": "ヴァルター・ゾマー", "Walter Winkler": "ヴァルター・ヴィンクラー", "Werner Giger": "ヴェルナー・ギーガー", "Werner Pfirter": "ヴェルナー・プフィルター", "Willi Bertsch": "ヴィリ・ベルチュ",
"Willi Scheidhauer": "ヴィリ・シャイトハウアー", "Winfried Fries": "ヴィンフリート・フリース", "Wolfgang Gedlich": "ヴォルフガング・ゲードリッヒ", "Wolfgang Rubel": "ヴォルフガング・ルーベル",
"Xaver Tschannen": "クサヴァー・チャンネン", "Y. Matsumoto": "マツモト・Y", "Yvon Duhamel": "イヴォン・デュアメル",
})
JA.update({
# ---- 1949〜1969年 ----
"A. Burton": "A・バートン", "A. Itoh": "イトウ・A", "A. Kralj": "A・クラリ", "A. Lawn": "A・ローン", "A. Mcalpine": "A・マカルパイン", "A. Parry": "A・パリー", "A. Vezzalini": "A・ヴェッツァリーニ",
"A.T. Lawton": "A.T.・ロートン", "A.W. Jones": "A.W.・ジョーンズ", "Aart Van Kooij": "アールト・ファン・コーイ", "Abbey de Kock": "アビー・デ・コック", "Adelmo Mandolini": "アデルモ・マンドリーニ",
"Agne Carlsson": "アグネ・カールソン", "Ake Dahli": "オーケ・ダーリ", "Akihiko Motohashi": "本橋明泰", "Alain Barbaroux": "アラン・バルバルー", "Alan Dugdale": "アラン・ダグデール",
"Alan Harris": "アラン・ハリス", "Alan Holmes": "アラン・ホームズ", "Alan Hunter": "アラン・ハンター", "Alan Shepherd": "アラン・シェパード", "Alan Trow": "アラン・トロウ",
"Alano Montanari": "アラーノ・モンタナーリ", "Albergian Louwes": "アルベルギアン・ラウエス", "Albert Beirle": "アルベルト・バイアレ", "Albert Montagne": "アルベール・モンターニュ",
"Albert Moule": "アルバート・モール", "Alberto Gandossi": "アルベルト・ガンドッシ", "Alberto Gomez": "アルベルト・ゴメス", "Alberto Picca": "アルベルト・ピッカ", "Alf Shaw": "アルフ・ショー",
"Alfredo Milani": "アルフレード・ミラーニ", "Alistair King": "アリステア・キング", "Allen Burt": "アレン・バート", "Allen Krupa": "アレン・クルーパ", "Andrea Georgeades": "アンドレア・ジョージアデス",
"Andreas Klaus": "アンドレアス・クラウス", "Andrew Duke": "アンドリュー・デューク", "Angelo Copeta": "アンジェロ・コペータ", "Angelo Marelli": "アンジェロ・マレッリ", "Angelo Tenconi": "アンジェロ・テンコーニ",
"Antero Ventoniemi": "アンテロ・ヴェントニエミ", "Anthony Fisher": "アンソニー・フィッシャー", "Anton Elbersen": "アントン・エルベルセン", "Antonie Paba": "アントニー・パバ", "Antonio Elizalde": "アントニオ・エリサルデ",
"Antonio de Simone": "アントニオ・デ・シモーネ", "Arciso Artesiani": "アルチーゾ・アルテジアーニ", "Artemio Cirelli": "アルテミオ・チレッリ", "Arthur Fegbli": "アルトゥール・フェグブリ",
"Arthur Wheeler": "アーサー・ウィーラー", "Artie Bell": "アーティ・ベル", "Arturo Paragues": "アルトゥーロ・パラゲス", "August Hobl": "アウグスト・ホーブル", "Auguste Goffin": "オーギュスト・ゴファン",
"B. Dickinson": "B・ディキンソン", "B. Spacciari": "B・スパッチャーリ", "Barry Cortvriend": "バリー・コルトフリント", "Barry Hodgkinson": "バリー・ホジキンソン", "Barry Scully": "バリー・スカリー",
"Benedetto Zambotti": "ベネデット・ザンボッティ", "Benedicto Caldarella": "ベネディクト・カルダレッラ", "Benjamin Savoye": "バンジャマン・サヴォワ", "Benoit Musy": "ブノワ・ミュジー",
"Beny Rood": "ベニー・ロート", "Bernard Lund": "バーナード・ランド", "Bernard Mahler": "ベルナール・マーラー", "Bernie Marrier": "バーニー・マリアー", "Bert Oosterhuis": "ベルト・オーステルハウス",
"Bert Schneider": "ベルト・シュナイダー", "Berthold Sieler": "ベルトルト・ジーラー", "Bill Beevers": "ビル・ビーヴァーズ", "Bill Collett": "ビル・コレット", "Bill Doran": "ビル・ドーラン",
"Bill Ivy": "ビル・アイビー", "Bill Lomas": "ビル・ロマス", "Bill Petch": "ビル・ペッチ", "Bill Prowting": "ビル・プラウティング", "Bill Roberton": "ビル・ロバートン", "Bill Robertson": "ビル・ロバートソン",
"Bill Webster": "ビル・ウェブスター", "Bill Wetzel": "ビル・ウェッツェル", "Billy Andersson": "ビリー・アンデション", "Bob Anderson": "ボブ・アンダーソン", "Bob Brown": "ボブ・ブラウン",
"Bob Ferguson": "ボブ・ファーガソン", "Bob Foster": "ボブ・フォスター", "Bob Gehring": "ボブ・ゲーリング", "Bob Matthews": "ボブ・マシューズ", "Bob McCurry": "ボブ・マッカリー",
"Bob McIntyre": "ボブ・マッキンタイア", "Bob Ritchie": "ボブ・リッチー", "Bob Rowbottom": "ボブ・ロウボトム", "Borro Castellani": "ボッロ・カステッラーニ", "Brian Ball": "ブライアン・ボール",
"Brian Carr": "ブライアン・カー", "Brian Dennis": "ブライアン・デニス", "Brian Purslow": "ブライアン・パースロー", "Brian Setchell": "ブライアン・セッチェル", "Brian Taggart": "ブライアン・タガート",
"Brian Walmsley": "ブライアン・ウォームズリー", "Bror-Erland Carlsson": "ブルール＝エルランド・カールソン", "Bruce Beale": "ブルース・ビール", "Bruno Bertacchini": "ブルーノ・ベルタッキーニ",
"Bruno Francisci": "ブルーノ・フランチシ", "Bruno Hofmann": "ブルーノ・ホフマン", "Bruno Ruffo": "ブルーノ・ルッフォ", "Bruno Veigel": "ブルーノ・ファイゲル", "Buddy Parriott": "バディ・パリオット",
"Buno Böhrer": "ブーノ・ベーラー", "Byron Black": "バイロン・ブラック", "C. Crawford": "C・クロフォード", "C. Dubols": "C・デュボワ", "C. Paragues": "C・パラゲス", "Campbell Donaghy": "キャンベル・ドナヒー",
"Carlo Bandirola": "カルロ・バンディローラ", "Carlo Marfetan": "カルロ・マルフェタン", "Carlo Ubbiali": "カルロ・ウッビアーリ", "Carlos Giro": "カルロス・ヒロ", "Carlos Rocamora": "カルロス・ロカモラ",
"Cas Swart": "カス・スワルト", "Cecil Sandford": "セシル・サンドフォード", "Celeste Cavaciuti": "チェレステ・カヴァチューティ", "Cesar Gracia": "セサル・グラシア", "Charlie Garner": "チャーリー・ガーナー",
"Charlie Mates": "チャーリー・メイツ", "Charlie Salt": "チャーリー・ソルト", "Charly Maubert": "シャルリー・モベール", "Chris Anderson": "クリス・アンダーソン", "Chris Conn": "クリス・コン",
"Chris Stormont": "クリス・ストーモント", "Chris Vincent": "クリス・ヴィンセント", "Clarrie Dunn": "クラリー・ダン", "Claudio Belotti": "クラウディオ・ベロッティ", "Claudio Mastellari": "クラウディオ・マステッラーリ",
"Clive Hunt": "クライヴ・ハント", "Colin Cross": "コリン・クロス", "Colin Lyster": "コリン・ライスター", "Cromie McCandless": "クロミー・マッキャンドレス", "D. Gedlich": "D・ゲードリッヒ",
"D. Lloyd": "D・ロイド", "D. Lock": "D・ロック", "D. Loyd": "D・ロイド", "D.T. Powell": "D.T.・パウエル", "Dan Shorey": "ダン・ショーリー", "Daniel Crivello": "ダニエル・クリヴェッロ",
"Daniel Lheraud": "ダニエル・レロー", "Dario Ambrosini": "ダリオ・アンブロジーニ", "Dave Chadwick": "デイヴ・チャドウィック", "Dave Degens": "デイヴ・デジェンス", "Dave Duncan": "デイヴ・ダンカン",
"Dave Wildman": "デイヴ・ワイルドマン", "David Whitworth": "デヴィッド・ウィットワース", "Davy Crawford": "デイヴィー・クロフォード", "Den Jarman": "デン・ジャーマン", "Dennis Ainsworth": "デニス・エインズワース",
"Dennis Fry": "デニス・フライ", "Dennis Gallagher": "デニス・ギャラガー", "Derek Ennett": "デレク・エネット", "Derek Farrant": "デレク・ファラント", "Derek Llee": "デレク・リー",
"Derek Minter": "デレク・ミンター", "Derek Russell": "デレク・ラッセル", "Derek Woodman": "デレク・ウッドマン", "Des Wright": "デス・ライト", "Desmond Wolff": "デズモンド・ウルフ",
"Dick Creith": "ディック・クリース", "Dick Knox": "ディック・ノックス", "Dick Pipes": "ディック・パイプス", "Dick Thompson": "ディック・トンプソン", "Dick Thomson": "ディック・トムソン",
"Dickie Dale": "ディッキー・デイル", "Dieter Falk": "ディーター・ファルク", "Dieter Krumpholz": "ディーター・クルンプホルツ", "Don Chapman": "ドン・チャップマン", "Don Ellis": "ドン・エリス",
"Don Haddow": "ドン・ハドウ", "Don Tickle": "ドン・ティックル", "Don Williams": "ドン・ウィリアムズ", "Douglas Beasley": "ダグラス・ビーズリー", "Dreikus Veer": "ドライクス・フェール",
"E. Cope": "E・コープ", "E. Frend": "E・フレンド", "E. Kyisa": "E・キーサ", "E.L. Griffith": "E.L.・グリフィス", "Ed Labelle": "エド・ラベル", "Eddie Crooks": "エディ・クルックス",
"Eduardo Salatino": "エドゥアルド・サラティーノ", "Edy Lenz": "エディ・レンツ", "Ellis Boyce": "エリス・ボイス", "Emilio Mendogni": "エミリオ・メンドーニ", "Emilio Soprani": "エミリオ・ソプラーニ",
"Endel Kiisa": "エンデル・キーサ", "Enrico Lorenzetti": "エンリコ・ロレンツェッティ", "Enrique Escuder": "エンリケ・エスクデル", "Eric Cheers": "エリック・チアーズ", "Eric Hinton": "エリック・ヒントン",
"Eric Houseley": "エリック・ハウズリー", "Eric Jones": "エリック・ジョーンズ", "Eric McPherson": "エリック・マクファーソン", "Eric Oliver": "エリック・オリバー", "Eric Pantilin": "エリック・パンティリン",
"Eric Wünsche": "エーリッヒ・ヴュンシェ", "Eriff Jenkins": "エリフ・ジェンキンス", "Ernesto Brambilla": "エルネスト・ブランビッラ", "Ernie Lyons": "アーニー・ライオンズ", "Ernie Oliver": "アーニー・オリバー",
"Ernie Ring": "アーニー・リング", "Ernst Degner": "エルンスト・デグナー", "Ernst Riedelbauch": "エルンスト・リーデルバウフ", "Ernst Weiss": "エルンスト・ヴァイス", "Errol Cowan": "エロール・コーワン",
"Evert Carlsson": "エヴェルト・カールソン", "Ewald Kluge": "エーヴァルト・クルーゲ", "Ewan Haldane": "ユーアン・ホールデン", "F. Aranda": "F・アランダ", "F. Camillieri": "F・カミッレーリ",
"F. Cufi": "F・クフィ", "F. Fry": "F・フライ", "F. Soler": "F・ソレル", "F. Villavelran": "F・ビジャベルラン", "Felice Benasedo": "フェリーチェ・ベナゼード", "Fergus Anderson": "ファーガス・アンダーソン",
"Firmin Dauwe": "フィルマン・ダウウェ", "Florian Camathias": "フロリアン・カマティアス", "Floyd Brown": "フロイド・ブラウン", "Fortunato Libanori": "フォルトゥナート・リバノーリ",
"Francis Flahaut": "フランシス・フラオー", "Franco Bertoni": "フランコ・ベルトーニ", "Franco Trabalzini": "フランコ・トラバルツィーニ", "Frank Burman": "フランク・バーマン", "Frank Fox": "フランク・フォックス",
"Frank Norris": "フランク・ノリス", "Frank Reynolds": "フランク・レイノルズ", "Frank Whiteway": "フランク・ホワイトウェイ", "Frans Fagerström": "フランス・ファーゲルストレム",
"Franta Stastny": "フランタ・シュタストニー", "Frantisek Helikar": "フランチシェク・ヘリカル", "Franziseh Bocek": "フランチシェク・ボチェク", "Franzisen Bartos": "フランチシェク・バルトシュ",
"Fred Redfern": "フレッド・レッドファーン", "Freddie Frith": "フレディ・フリス", "Frederic Moreira": "フレデリック・モレイラ", "Frederick Cook": "フレデリック・クック", "Fritz Kläger": "フリッツ・クレーガー",
"Fritz Messerli": "フリッツ・メッセルリ", "Fritz Meyer": "フリッツ・マイヤー", "Fron Purslow": "フロン・パースロー", "Fumio Ito": "伊藤史朗", "G. Andrews": "G・アンドリューズ", "G. Costa": "G・コスタ",
"G. Julian": "G・ジュリアン", "G. Lombardi": "G・ロンバルディ", "G.A. Catlin": "G.A.・キャトリン", "G.A. Reeve": "G.A.・リーヴ", "G.A. Simmonds": "G.A.・シモンズ", "Gabriel Corsin": "ガブリエル・コルサン",
"Gary Dickinson": "ゲイリー・ディキンソン", "Gary Hocking": "ゲイリー・ホッキング", "Gaston Biscia": "ガストン・ビシア", "Geoff Duke": "ジェフ・デューク", "Geoff Monty": "ジェフ・モンティ",
"Geoff Read": "ジェフ・リード", "Geoffrey Tanner": "ジェフリー・タナー", "Georg Braun": "ゲオルク・ブラウン", "George Brown": "ジョージ・ブラウン", "George Costain": "ジョージ・コスティン",
"George Leigh": "ジョージ・リー", "George Murphy": "ジョージ・マーフィー", "George Northwood": "ジョージ・ノースウッド", "George Purvis": "ジョージ・パーヴィス", "George Rockett": "ジョージ・ロケット",
"George Salt": "ジョージ・ソルト", "Georges Comy": "ジョルジュ・コミ", "Gerald Robarts": "ジェラルド・ロバーツ", "Gerold Klinger": "ゲロルト・クリンガー", "Gerrit Ten Kate": "ヘリット・テン・カーテ",
"Gerry Turner": "ジェリー・ターナー", "Gianni Leoni": "ジャンニ・レオーニ", "Giichi Suzuki": "鈴木義一", "Gijs Lagervey": "ヘイス・ラーヘルフェイ", "Gijs Oosterbaan": "ヘイス・オーステルバーン",
"Gilbert Argo": "ジルベール・アルゴ", "Gilberto Milani": "ジルベルト・ミラーニ", "Giovanni Burlando": "ジョヴァンニ・ブルランド", "Giuseppe Colnago": "ジュゼッペ・コルナーゴ",
"Giuseppe Dardanello": "ジュゼッペ・ダルダネッロ", "Giuseppe Lattanzi": "ジュゼッペ・ラッタンツィ", "Giuseppe Mantelli": "ジュゼッペ・マンテッリ", "Giuseppe Matucci": "ジュゼッペ・マトゥッチ",
"Graham Dickson": "グレアム・ディクソン", "Graham Downes": "グレアム・ダウンズ", "Graham Smith": "グレアム・スミス", "Grenville Pennington": "グレンヴィル・ペニントン", "Griff Jenkins": "グリフ・ジェンキンス",
"Guido Leoni": "グイド・レオーニ", "Guido Paciocca": "グイド・パチョッカ", "Gustav Havel": "グスタフ・ハヴェル", "Guy Ligier": "ギ・リジェ", "György Kurucz": "ジェルジ・クルツ",
"Günter Beer": "ギュンター・ベーア", "Günther Borgesdiek": "ギュンター・ボルゲスディーク", "H. Beer": "H・ベーア", "H. Karlsson": "H・カールソン", "H. Takahashi": "タカハシ・H",
"H. Yamashita": "ヤマシタ・H", "H.A. Pearce": "H.A.・ピアース", "Hannu Kuparinen": "ハンヌ・クパリネン", "Hans Baltisberger": "ハンス・バルティスベルガー", "Hans Bartl": "ハンス・バルトル",
"Hans Fischer": "ハンス・フィッシャー", "Hans-Günter Jäger": "ハンス＝ギュンター・イェーガー", "Hans Haldemann": "ハンス・ハルデマン", "Hans Pesl": "ハンス・ペスル",
"Hans Thorn-Prikker": "ハンス・トルン＝プリッカー", "Hans-Georg Anscheidt": "ハンス＝ゲオルグ・アンシャイト", "Hans-Joachim Scheel": "ハンス＝ヨアヒム・シェール", "Hans-Siegfried Gläser": "ハンス＝ジークフリート・グレーザー",
"Harold Daniell": "ハロルド・ダニエル", "Harold Riley": "ハロルド・ライリー", "Harris Healey": "ハリス・ヒーリー", "Harry Grant": "ハリー・グラント", "Harry Hinton": "ハリー・ヒントン",
"Harry Plews": "ハリー・プリューズ", "Harry Reynolds": "ハリー・レイノルズ", "Harry Turner": "ハリー・ターナー", "Harry Voice": "ハリー・ヴォイス", "Haruo Koshino": "コシノ・ハルオ",
"Heinz Kauert": "ハインツ・カウエルト", "Heinz Rosner": "ハインツ・ロスナー", "Helmut Hallmeier": "ヘルムート・ハルマイヤー", "Herbert Denzler": "ヘルベルト・デンツラー", "Herman Gablenz": "ヘルマン・ガブレンツ",
"Hermann Paul Müller": "ヘルマン・パウル・ミュラー", "Holger Ekström": "ホルガー・エークストレム", "Horacio Maffia": "オラシオ・マフィア", "Hiroshi Hasegawa": "ハセガワ・ヒロシ", "Horst Fügner": "ホルスト・フュークナー",
"Hubert Luttenberg": "フーベルト・ルッテンベルク", "Hugh Anderson": "ヒュー・アンダーソン", "Hugo Pochettino": "ウーゴ・ポチェッティーノ", "I. Sauter": "I・ザウター", "I. Yamashita": "ヤマシタ・I",
"Ian McGuffie": "イアン・マクガフィー", "Ian McGregor": "イアン・マクレガー", "Ian Plumridge": "イアン・プラムリッジ", "Jean Noel Burne": "ジャン＝ノエル・ビュルヌ", "Isamu Kasuya": "カスヤ・イサム",
"Isao Morishita": "モリシタ・イサオ", "Ivan Schuman": "イヴァン・シューマン", "Ivor Lloyd": "アイヴァー・ロイド", "J. Acosta": "J・アコスタ", "J. Albisser": "J・アルビッサー", "J. Bultó": "J・ブルト",
"J. Lloyd": "J・ロイド", "J. O'Brien": "J・オブライエン", "J. Raffeld": "J・ラッフェルト", "J. Sato": "サトウ・J", "J. Stefe": "J・シュテーフェ", "J. Unterladstatter": "J・ウンターラートシュテッター",
"J.D. Anderson": "J.D.・アンダーソン", "J.D. Lawley": "J.D.・ローリー", "J.G. Horne": "J.G.・ホーン", "Jaap Iesberts": "ヤープ・イースベルツ", "Jack Ahearn": "ジャック・アハーン",
"Jack Bailey": "ジャック・ベイリー", "Jack Brett": "ジャック・ブレット", "Jack Bullock": "ジャック・ブロック", "Jack Forrest": "ジャック・フォレスト", "Jack Gow": "ジャック・ガウ", "Jack Linah": "ジャック・ライナ",
"Jack Lindh": "ジャック・リンド", "Jack Saunders": "ジャック・ソーンダース", "Jack Shannon": "ジャック・シャノン", "Jack Simpson": "ジャック・シンプソン", "Jack Wood": "ジャック・ウッド",
"Jackie Wood": "ジャッキー・ウッド", "Jacques Collot": "ジャック・コロ", "Jacques Insermini": "ジャック・アンセルミニ", "Jacques Roca": "ジャック・ロカ", "James Beckett": "ジェームズ・ベケット",
"Jan Hennek": "ヤン・ヘンネク", "Jannie Stander": "ヤニー・スタンダー", "Jean Claude Guenard": "ジャン＝クロード・グナール", "Jean Francois Chaffin": "ジャン＝フランソワ・シャファン",
"Jean Guy Duval": "ジャン＝ギ・デュヴァル", "Jean Louis Vergnais": "ジャン＝ルイ・ヴェルニェ", "Jean Pierre Bayle": "ジャン＝ピエール・ベイル", "Jean Pierre Beltoise": "ジャン＝ピエール・ベルトワーズ",
"Jeff Mawby": "ジェフ・モービー", "Jeff Tate": "ジェフ・テイト", "Jeffry De Vries": "ジェフリー・デ・フリース", "Jim Pink": "ジム・ピンク", "Jim Redman": "ジム・レッドマン", "Jim Tompsett": "ジム・トンプセット",
"Jimmy Buchan": "ジミー・バカン", "Jimmy Jones": "ジミー・ジョーンズ", "Jimmy Morton": "ジミー・モートン", "Jiri Kostir": "イジー・コスティル", "Jock West": "ジョック・ウェスト", "Joe Dunphy": "ジョー・ダンフィー",
"Joe Glazebrook": "ジョー・グレイズブルック", "Joe Tate": "ジョー・テイト", "Joe Wright": "ジョー・ライト", "John Blanchard": "ジョン・ブランチャード", "John Brown": "ジョン・ブラウン",
"John Buckner": "ジョン・バックナー", "John Burgess": "ジョン・バージェス", "John Clark": "ジョン・クラーク", "John Cooper": "ジョン・クーパー", "John Denton": "ジョン・デントン",
"John Farnsworth": "ジョン・ファーンズワース", "John Gabites": "ジョン・ガビテス", "John Hartle": "ジョン・ハートル", "John Hempleman": "ジョン・ヘンプルマン", "John Hurlstone": "ジョン・ハールストン",
"John Kidson": "ジョン・キッドソン", "John Lewis": "ジョン・ルイス", "John Lockett": "ジョン・ロケット", "John Lothar": "ジョン・ロザー", "John Marcotte": "ジョン・マルコット",
"John Ringwood": "ジョン・リングウッド", "John Shacklady": "ジョン・シャックレディ", "John Simmonds": "ジョン・シモンズ", "John Somers": "ジョン・ソマーズ", "John Storr": "ジョン・ストー",
"John Surtees": "ジョン・サーティース", "John Williamson": "ジョン・ウィリアムソン", "Johnnie Rae": "ジョニー・レイ", "Johnny Grace": "ジョニー・グレース", "Joop Vogelzang": "ヨープ・フォーヘルザング",
"Jorge Kissling": "ホルヘ・キスリング", "Jorge Terengo": "ホルヘ・テレンゴ", "Josef Autengruber": "ヨーゼフ・アウテングルーバー", "Josep Maria Busquets": "ジョゼップ・マリア・ブスケツ",
"Jouko Ryhanen": "ヨウコ・リュハネン", "Juan Bertran": "フアン・ベルトラン", "Juan Llobet": "フアン・リョベト", "Juan Salatino": "フアン・サラティーノ", "Jukka Petaja": "ユッカ・ペタヤ",
"Jyun Hamano": "ハマノ・ジュン", "Jüri Randla": "ユリ・ランドラ", "K. Matsushima": "マツシマ・K", "K. Muromachi": "ムロマチ・K", "Karaber Samardjian": "カラベル・サマルジャン",
"Karl Hofmann": "カール・ホフマン", "Karl Kronmueller": "カール・クロンミュラー", "Karl Lottes": "カール・ロッテス", "Karl Peters": "カール・ペータース", "Karl Recktenwald": "カール・レクテンヴァルト",
"Karl-Heinz Ewig": "カール＝ハインツ・エーヴィヒ", "Karl-Heinz Scheifel": "カール＝ハインツ・シャイフェル", "Kees Koster": "ケース・コステル", "Keith Bryen": "キース・ブライエン",
"Ken Draper": "ケン・ドレイパー", "Ken Harwood": "ケン・ハーウッド", "Ken Kavanagh": "ケン・カヴァナー", "Ken King": "ケン・キング", "Ken Mudford": "ケン・マドフォード", "Ken Swallow": "ケン・スワロー",
"Ken Tostevin": "ケン・トステヴィン", "Ken Tully": "ケン・タリー", "Kenjiro Tanaka": "田中健二郎", "Kevin Cass": "ケヴィン・キャス", "Kevin Webster": "ケヴィン・ウェブスター",
"Klaus Enderlein": "クラウス・エンダーライン", "Klaus Hamelmann": "クラウス・ハメルマン", "Kunimitsu Takahashi": "高橋国光", "Kuniomi Magamatsu": "マガマツ・クニオミ", "Kurt Knopf": "クルト・クノプフ",
"L. Fassl": "L・ファスル", "L. Lawlor": "L・ローラー", "L. Roth": "L・ロート", "L. Van Rijswijk": "L・ファン・ライスウェイク", "L.T. Simpson": "L.T.・シンプソン", "Ladi Richter": "ラディ・リヒター",
"Lanfranco Baviera": "ランフランコ・バヴィエーラ", "Laurence Povey": "ローレンス・ポーヴィー", "Laurie Flury": "ローリー・フルーリー", "Lee Allen": "リー・アレン", "Leen Reehorst": "レーン・レーホルスト",
"Len Aislabie": "レン・エイズラビー", "Len Bayliss": "レン・ベイリス", "Len Ireland": "レン・アイルランド", "Len Parry": "レン・パリー", "Len Rutherford": "レン・ラザフォード", "Leo Simpson": "レオ・シンプソン",
"Leon Martin": "レオン・マルタン", "Leonard Atlee": "レナード・アトリー", "Les Griffiths": "レス・グリフィス", "Les Kempster": "レス・ケンプスター", "Leslie Graham": "レスリー・グラハム",
"Libero Liberati": "リベロ・リベラティ", "Limberg Moreira": "リンベルグ・モレイラ", "Llewelyn Ranson": "ルウェリン・ランソン", "Lo Simons": "ロー・シモンス", "Louis Bernagozzi": "ルイ・ベルナゴッツィ",
"Louis Carr": "ルイス・カー", "Louis Carter": "ルイス・カーター", "Luigi Taveri": "ルイジ・タベリ", "Luigi Zinzani": "ルイジ・ジンザーニ", "M. Akamatsu": "アカマツ・M", "M. Coopey": "M・クーピー",
"M. Dietrich": "M・ディートリッヒ", "M. Hatherill": "M・ハザリル", "M. Templeton": "M・テンプルトン", "Malcom Stanton": "マルコム・スタントン", "Manliefe Barrington": "マンリーフ・バリントン",
"Marcel Beauvais": "マルセル・ボーヴェ", "Marcel Toussaint": "マルセル・トゥーサン", "Marcello Cama": "マルチェッロ・カーマ", "Mark McCausland": "マーク・マコーズランド", "Martinus van Son": "マルティヌス・ファン・ソン",
"Martyn Hayward": "マーティン・ヘイワード", "Marzilio Chizzini": "マルツィリオ・キッツィーニ", "Massimo Genevini": "マッシモ・ジェネヴィーニ", "Maurice Bula": "モーリス・ビュラ", "Maurice Cann": "モーリス・キャン",
"Maurice Hawtorne": "モーリス・ホーソーン", "Maurice Quincey": "モーリス・クインシー", "Maurice de Polo": "モーリス・ド・ポロ", "Michael McStay": "マイケル・マクステイ", "Michael Roche": "マイケル・ロシュ",
"Michael Schneider": "ミヒャエル・シュナイダー", "Michel Valentin": "ミシェル・ヴァランタン", "Michelle Duff": "ミシェル・ダフ", "Michio Ichino": "イチノ・ミチオ", "Mick Featherstone": "ミック・フェザーストーン",
"Mike Hailwood": "マイク・ヘイルウッド", "Mike O'Rourke": "マイク・オルーク", "Mitsuo Itoh": "伊藤光夫", "Monty Buxton": "モンティ・バクストン", "Morisuka Yamashita": "ヤマシタ・モリスケ",
"Morry Low": "モリー・ロウ", "Moto Kitano": "北野元", "Máté Laczko": "マーテー・ラツコ", "Naomi Taniguchi": "谷口尚己", "Neil Hodgson Hodgins": "ニール・ホジソン・ホジンズ", "Nello Pagani": "ネロ・パガーニ",
"Neville Landrebe": "ネヴィル・ランドレーブ", "Nikolai Sevostianov": "ニコライ・セヴォスチャノフ", "Nino Grieco": "ニーノ・グリエコ", "Noel McCutcheon": "ノエル・マカッチョン", "O. Hansen": "O・ハンセン",
"Oliver Howe": "オリバー・ハウ", "Onorato Francone": "オノラート・フランコーネ", "Orlando Valdinoci": "オルランド・ヴァルディノーチ", "Oscar Clemencigh": "オスカル・クレメンチグ", "Oswald Dittrich": "オスヴァルト・ディトリッヒ",
"Otello Spadoni": "オテッロ・スパドーニ", "Othmar Drixl": "オトマール・ドリクスル", "Otto Daiker": "オットー・ダイカー", "Owen Greenwood": "オーウェン・グリーンウッド", "P. Fuhrer": "P・フューラー",
"P. Kiisa": "P・キーサ", "P.B. Fahey": "P.B.・フェイ", "P.G. Inchley": "P.G.・インチリー", "Paddy Driver": "パディ・ドライバー", "Patrick Manning": "パトリック・マニング", "Patrick Plunkett": "パトリック・プランケット",
"Paul Lodewijkx": "パウル・ローデワイクス", "Pavel Stavicek": "パヴェル・スタヴィチェク", "Pedro Alvarez": "ペドロ・アルバレス", "Pedro Rosenthal": "ペドロ・ローゼンタール", "Pertti Leinonen": "ペルッティ・レイノネン",
"Pete Bettison": "ピート・ベティソン", "Peter Chatterton": "ピーター・チャタートン", "Peter Darvill": "ピーター・ダーヴィル", "Peter Davey": "ピーター・デイヴィー", "Peter Eser": "ペーター・エーザー",
"Peter Evans": "ピーター・エヴァンズ", "Peter Ferbrache": "ピーター・ファーブラッシュ", "Peter Horton": "ピーター・ホートン", "Peter Humber": "ピーター・ハンバー", "Peter Knees": "ペーター・クネース",
"Peter Middleton": "ピーター・ミドルトン", "Peter Murphy": "ピーター・マーフィー", "Peter Pawson": "ピーター・ポーソン", "Peter Preston": "ピーター・プレストン", "Phil Carter": "フィル・カーター",
"Phil Heath": "フィル・ヒース", "Phil O'Brien": "フィル・オブライエン", "Philip Palmer": "フィリップ・パーマー", "Philippe Canoui": "フィリップ・カヌイ", "Phillip McCallen": "フィリップ・マッカレン",
"Pierre James": "ピエール・ジェームズ", "Pierre Vervroegen": "ピエール・フェルフルーヘン", "Piet Bakker": "ピート・バッケル", "Piet Knijnenburg": "ピート・クナイネンブルフ", "Pietro Mencaglia": "ピエトロ・メンカーリャ",
"Priem Rozenberg": "プリーム・ローゼンベルフ", "R. Creith": "R・クリース", "R. Ftll": "R・フトル", "R. Siriwardena": "R・シリワルデナ", "R.A. Graham": "R.A.・グラハム", "R.E. Geeson": "R.E.・ギーソン",
"R.M. Udall": "R.M.・ユードール", "Raffaele Alberti": "ラファエレ・アルベルティ", "Ralf Engelhardt": "ラルフ・エンゲルハルト", "Ralf Swegan": "ラルフ・スウィーガン", "Rally Dean": "ラリー・ディーン",
"Ralph Bryans": "ラルフ・ブライアンズ", "Ralph Rensen": "ラルフ・レンセン", "Ralph Wijesinghe": "ラルフ・ウィジェシンゲ", "Ramon Torras": "ラモン・トラス", "Raoul Kissling": "ラウール・キスリング",
"Raphaël Orinel": "ラファエル・オリネル", "Ray Amm": "レイ・アム", "Ray Beaumont": "レイ・ボーモント", "Ray Breingan": "レイ・ブレインガン", "Ray Fay": "レイ・フェイ", "Ray Petty": "レイ・ペティ",
"Ray Spence": "レイ・スペンス", "Ray Travers": "レイ・トラヴァース", "Raymond Bogaerdt": "レイモンド・ボハールト", "Raymond Hanset": "レイモン・アンセ", "Raymond Shaw": "レイモンド・ショー",
"Reg Armstrong": "レッグ・アームストロング", "Remo Venturi": "レーモ・ヴェントゥーリ", "Renato Magi": "レナート・マージ", "Renato Sartori": "レナート・サルトーリ", "Rene Goetz": "ルネ・ゲッツ",
"Rex Avery": "レックス・エイヴリー", "Rex Butcher": "レックス・ブッチャー", "Riccardo Quintanilla": "リカルド・キンタニージャ", "Richard Ingram": "リチャード・イングラム", "Richard Thomas": "リチャード・トーマス",
"Rick Schell": "リック・シェル", "Ricky Porter": "リッキー・ポーター", "Rob Fitton": "ロブ・フィットン", "Robert Haldane": "ロバート・ホールデン", "Robert King": "ロバート・キング", "Robert Knott": "ロバート・ノット",
"Robert Lusk": "ロバート・ラスク", "Robert McCracken": "ロバート・マクラッケン", "Robert Messina": "ロベルト・メッシーナ", "Roberto Colombo": "ロベルト・コロンボ", "Roberto Teneggi": "ロベルト・テネッジ",
"Robin Sherry": "ロビン・シェリー", "Rod Coleman": "ロッド・コールマン", "Roger Barker": "ロジャー・バーカー", "Roger Mailes": "ロジャー・メイルズ", "Roger Montane": "ロジェ・モンタネ",
"Roland Felgenheier": "ローラント・フェルゲンハイアー", "Roland Föll": "ローラント・フェル", "Roland Heck": "ローラント・ヘック", "Roland Pike": "ローランド・パイク", "Roland Schnell": "ローラント・シュネル",
"Rolf Schmid": "ロルフ・シュミート", "Roly Capner": "ローリー・キャプナー", "Romolo Ferri": "ロモロ・フェッリ", "Ron Grant": "ロン・グラント", "Ron Langston": "ロン・ラングストン", "Ron Miles": "ロン・マイルズ",
"Ron Robinson": "ロン・ロビンソン", "Ron Wilson": "ロン・ウィルソン", "Ronald Cousins": "ロナルド・カズンズ", "Ronald Mead": "ロナルド・ミード", "Ross Hannan": "ロス・ハナン", "Roy Boughey": "ロイ・ボーイー",
"Roy Evans": "ロイ・エヴァンズ", "Roy Robinson": "ロイ・ロビンソン", "Rudolf Gläser": "ルドルフ・グレーザー", "Rudolf Grimas": "ルドルフ・グリマス", "Rudolf Schmälzle": "ルドルフ・シュメルツレ",
"Rudolf Thalhammer": "ルドルフ・タールハマー", "Rudolph Kaiser": "ルドルフ・カイザー", "Rudy Allison": "ルディ・アリソン", "Rupert Hollaus": "ルパート・ホラウス", "S. Matti": "S・マッティ",
"S. Mimuro": "ミムロ・S", "S. Perkins": "S・パーキンス", "S. Pomesano": "S・ポメザーノ", "S.A. Sørensen": "S.A.・ソーレンセン", "S.A. Willis": "S.A.・ウィリス", "S.G.W. Lawley": "S.G.W.・ローリー",
"S.J. Florjan": "S.J.・フロリャン", "Sadao Shimazaki": "シマザキ・サダオ", "Sakari Järvimaa": "サカリ・ヤルヴィマー", "Sam Cooper": "サム・クーパー", "Sammy Miller": "サミー・ミラー",
"Sandro Artusi": "サンドロ・アルトゥージ", "Sante Geminiani": "サンテ・ジェミニアーニ", "Scott Whiteside": "スコット・ホワイトサイド", "Seichi Suzuki": "スズキ・セイイチ", "Shunkichi Masuda": "マスダ・シュンキチ",
"Sid Jensen": "シド・ジェンセン", "Sid Lawton": "シド・ロートン", "Sid Mizen": "シド・マイゼン", "Sijbren Postma": "セイブレン・ポストマ", "Simon Sandys-Winsch": "サイモン・サンディーズ＝ウィンシュ",
"Stan Brassley": "スタン・ブラスリー", "Stanislav Malina": "スタニスラフ・マリナ", "Steve Aspin": "スティーヴ・アスピン", "Steve Jolly": "スティーヴ・ジョリー", "Stuart Graham": "スチュアート・グラハム",
"Stuart Morin": "スチュアート・モリン", "Sven Andersson": "スヴェン・アンデション", "T. Lego": "T・レゴ", "T. Yoring": "T・ヨーリング", "Tarquinio Provini": "タルクィニオ・プロヴィーニ",
"Tauno Nurmi": "タウノ・ヌルミ", "Terry Grotefeld": "テリー・グロートフェルド", "Terry Shepherd": "テリー・シェパード", "Teuvo Laakso": "テウヴォ・ラークソ", "Theo Louwes": "テオ・ラウエス",
"Tim Coopey": "ティム・クーピー", "Tino Forconi": "ティーノ・フォルコーニ", "Tom Gill": "トム・ギル", "Thomas Gill": "トーマス・ギル", "Tom Phillis": "トム・フィリス", "Tom Thorp": "トム・ソープ",
"Tom Walker": "トム・ウォーカー", "Tommy Holmes": "トミー・ホームズ", "Tommy McEwan": "トミー・マキューアン", "Tommy Robinson": "トミー・ロビンソン", "Tommy Wood": "トミー・ウッド",
"Toni Schmitz": "トニ・シュミッツ", "Tony Godfrey": "トニー・ゴドフリー", "Tony Heaton": "トニー・ヒートン", "Tony McAlpine": "トニー・マカルパイン", "Tony Ovens": "トニー・オーヴェンス",
"Trevor Farnsworth": "トレヴァー・ファーンズワース", "Ulf Gate": "ウルフ・ガーテ", "Ulf Svensson": "ウルフ・スヴェンソン", "Umberto Braga": "ウンベルト・ブラーガ", "Umberto Masetti": "ウンベルト・マセッティ",
"Umberto Plebani": "ウンベルト・プレバーニ", "V. Corsin": "V・コルサン", "V. Perry": "V・ペリー", "Vaclav Parus": "ヴァーツラフ・パルス", "Vagn Stevnhoved": "ヴァウン・ステウンホヴェズ",
"Veikko Sulasaari": "ヴェイッコ・スラサーリ", "Vernon Cottle": "ヴァーノン・コトル", "Vincenzo Zanzi": "ヴィンチェンツォ・ザンツィ", "W. Maddrick": "W・マドリック", "W. Nelson": "W・ネルソン",
"W. Petch": "W・ペッチ", "W. Stewart": "W・スチュワート", "W.C. Guthrie": "W.C.・ガスリー", "W.H. Spence": "W.H.・スペンス", "Walter Brehme": "ヴァルター・ブレーメ", "Walter Hancock": "ウォルター・ハンコック",
"Walter Reichert": "ヴァルター・ライヒェルト", "Walter Vogel": "ヴァルター・フォーゲル", "Walter Zeller": "ヴァルター・ツェラー", "Werner Bergold": "ヴェルナー・ベルゴルト", "Werner Gerber": "ヴェルナー・ゲルバー",
"Werner Haas": "ヴェルナー・ハース", "Werner Musiol": "ヴェルナー・ムジオール", "Wilf Billington": "ウィルフ・ビリントン", "Wilf Herron": "ウィルフ・ヘロン", "Wilhem Lecke": "ヴィルヘルム・レッケ",
"William Hall": "ウィリアム・ホール", "William Sharp": "ウィリアム・シャープ", "Willie Wilshere": "ウィリー・ウィルシャー", "Willy Lips": "ウィリー・リップス", "Wolfgang Brandt": "ヴォルフガング・ブラント",
"Wolfgang Gast": "ヴォルフガング・ガスト", "Wolfgang Reinhard": "ヴォルフガング・ラインハルト", "Wolfgang Stropek": "ヴォルフガング・シュトローペク", "Xaver Heiss": "クサヴァー・ハイス",
"Yasuharu Yuzawa": "ユザワ・ヤスハル", "Yasuho Shigeno": "シゲノ・ヤスホ", "Yoshikazu Sunako": "砂子義一", "Yoshimi Katayama": "片山義美", "Z. Gleed": "Z・グリード",
})
JA.update({"John Anderson": "ジョン・アンダーソン", "Roy Ingram": "ロイ・イングラム", "Ian Burne": "イアン・バーン", "David Lloyd": "デヴィッド・ロイド"})
JA.update({"Takashi Yasuda": "ヤスダ・タカシ"})
